### ISSUE TITLE
Repeated emit of 'change' event

### ISSUE THREAD

**Issue by DaHofa** [ceramicnetwork/js-ceramic#1026]
I observe a repeated emit of the event 'change' on a ceramic document, when doing periodically syncing. I am using the http client connected to https://localhost:7007

The bug appears in the function _syncState in document.js, where the comparison 

` JSON.stringify(common_1.DoctypeUtils.serializeState(this.state)) !== JSON.stringify(state) `

always fails since `state`contains an anchor-proof **and** date, when the proof is scheduled for, however, `this.state` has the `anchorScheduleDate` as `null`. This is also enforced in the `deserializeState` function.

**Comment by oed** [comment]
Thanks for reporting @DaHofa. We are currently in the process of redesigning how we use and emit events in the Ceramic api. So this will likely be fixed as part of that. 
Paging @ukstv for visibility.

**Comment by ukstv** [comment]
Should be fixed in https://github.com/ceramicnetwork/js-ceramic/pull/1150, as it deserialises the state, and then uses `DoctypeUtils.statesEqual` now.
