### ISSUE TITLE
Exceptions thrown while processing anchor service response crash the process

### ISSUE THREAD

**Issue by stbrody** [ceramicnetwork/js-ceramic#1052]
During some manual testing I saw my ceramic daemon crash with the following log:
```
Ceramic API running on port 7007
/home/spencer/js-ceramic1/node_modules/rxjs/internal/util/hostReportError.js:4
    setTimeout(function () { throw err; }, 0);
                             ^

TimeoutError: request timed out
    at maybeThrowTimeoutError (/home/spencer/js-ceramic1/node_modules/ipfs-core/node_modules/ipfs-core-utils/src/with-timeout-option.js:42:15)
    at /home/spencer/js-ceramic1/node_modules/ipfs-core/node_modules/ipfs-core-utils/src/with-timeout-option.js:96:9
    at async Dispatcher.retrieveCommit (/home/spencer/js-ceramic1/packages/core/lib/dispatcher.js:156:24)
    at async Document._fetchLog (/home/spencer/js-ceramic1/packages/core/lib/document.js:153:24)
    at async /home/spencer/js-ceramic1/packages/core/lib/document.js:136:29
    at async run (/home/spencer/js-ceramic1/node_modules/p-queue/dist/index.js:163:29) {
  code: 'ERR_TIMEOUT'
}
```

This can be repro'd by putting the line `throw new Error("fake timeout")` right before [this line](https://github.com/ceramicnetwork/js-ceramic/blob/283b3c27737721d36dc7d73426dc8e110df42226/packages/core/src/document.ts#L330), starting the daemon, creating a document, and waiting for it to be anchored.

The problem seems to be if an exception is thrown within [this code](https://github.com/ceramicnetwork/js-ceramic/blob/283b3c27737721d36dc7d73426dc8e110df42226/packages/core/src/document.ts#L589-L623)

**Comment by stbrody** [comment]
@ukstv do you want to pick this up since it's in code you've been working in?

**Comment by ukstv** [comment]
Feel free to add an error handler there :)

**Comment by ukstv** [comment]
Current upstream puts the anchoring errors straight to the log: https://github.com/ceramicnetwork/js-ceramic/blob/master/packages/core/src/state-management/state-manager.ts#L149 So, the issue could be considered fixed.
