### ISSUE TITLE
DocID instanceof checks are brittle

### ISSUE THREAD

**Issue by stbrody** [ceramicnetwork/js-ceramic#1057]
[DocRef uses `instanceof`](https://github.com/ceramicnetwork/js-ceramic/blob/7a4af4de173550a597b3fb431942a2b9bc444dff/packages/docid/src/doc-ref.ts#L47) to check if its input is a DocID or CommitID.  This check is brittle and failing erroneously in integration tests, preventing passing around DocIDs in some places.

**Comment by ukstv** [comment]
See #1059

**Comment by ukstv** [comment]
Check if that `instanceof` fixes the issue you have, and feel free to merge the PR.

**Comment by stbrody** [comment]
Confirmed that this fixed the issue I was having.  Thanks!
