### ISSUE TITLE
"Unknown DID" error when writing document with a `key-did-provider` DID

### ISSUE THREAD

**Issue by jeffkhull** [ceramicnetwork/js-ceramic#1077]
**Describe the bug**
Error following the [ceramic tutorial](https://developers.ceramic.network/build/authentication/) using `key-did-provider`.  Getting error "Unknown DID" when writing document

**To Reproduce**
1. Run a local ceramic node using `ceramic daemon` and initialize the ceramic client with your locally-running ceramic instance
```js
  const ceramic = new CeramicClient(API_URL)
```
2. Create a new random DID with 
```js
  import { randomBytes } from "@stablelib/random"

  const seed = randomBytes(32)
  const provider = new Ed25519Provider(seed)
  await ceramic.setDIDProvider(provider)
```
3. Try to write a document.  For example:
```sh
  const doc = await ceramic.createDocument("tile", {
    content: { foo: "bar" },
    metadata: {
      schema: "ceramic://kyz123...456",
      controllers: ["did:3:kyz123...456"],
      family: "doc family",
    },
  })
```
4. You should get the error "UnhandledPromiseRejectionWarning: Error: Unknown DID: did:key:[your DID]

**Expected behavior**
Should connect to ceramic and write a document

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.10
 - Node v12.20
 - @ceramicnetwork/http-client v0.9.6

**Comment by stbrody** [comment]
As best I can tell, the "Unknown DID" error is coming from [this line](https://github.com/ceramicnetwork/key-did-provider-ed25519/blob/bdb4df1bae5c18bae5caa7684eccf5f80815d0e5/src/index.ts#L100) in the `key-did-provider-ed25519` package.  This seems to suggest that the DID you are authenticated as is different than the DID whose signature is being requested, which in this case would be the DID specified in the `controllers` array.  Are you sure that the DID you are specifying as the controller in the document's metadata is the same DID being provided by the `Ed25519Provider` you construct and give in `ceramic.setDIDProvider`?

**Comment by jeffkhull** [comment]
Hey @stbrody, thanks for your fast and detailed response.

It seems the quick-start tutorial is missing a couple of lines of code, I was indeed not using the right value in the controllers array.  These lines were missing, from correct usage of Ed25519Provider:

```js
const did = new DID({ provider, resolver: KeyResolver.getResolver() })
await did.authenticate()
```

Now I am running into a new error when trying to write the document, `UnhandledPromiseRejectionWarning: Error: fromBytes: invalid docid, does not include docid codec`

[here](https://github.com/jeffkhull/js-ipld-examples/blob/main/src/ceramic-test.ts) is the full code of my current example.  I'm just getting started with ceramic, so not sure if there is something else wrong with the metadata of the doc I'm trying to write...maybe the value in the schema field (which is totally made up):

```js
  const doc = await ceramic.createDocument("tile", {
    content: { foo: "bar" },
    metadata: {
      schema: "ceramic://kyz123456",
      controllers: [did.id],
      family: "doc family",
    },
  })
```

Note: maybe once I get it working, if helpful, I can submit a PR back to this portion of the getting started docs.

**Comment by oed** [comment]
That's weird. The `CeramicClient` should definitely include the KeyResolver by default 🤔

**Comment by jeffkhull** [comment]
Quick update on this....  I'm now trying to give idx a try as a provider, and I'm trying to follow the guide [here](https://developers.idx.xyz/build/authentication/).  The guide says to set a DID provider this way so that `idx.get` can be used:

```js
await ceramic.setDIDProvider(...)
await idx.get('anAlias') // uses authenticated DID
```
The idx guide points to the [ceramic docs](https://developers.ceramic.network/build/authentication/) on authentication, but the ceramic docs do not specify how to generate a DID provider using IDX, so that it can be passed to `ceramic.setDIDProvider(...)`.  I have tried searching through the `js-idx` repo, and I don't see any examples there.  Maybe I am missing it?

**Comment by stbrody** [comment]
[this page](https://developers.ceramic.network/build/authentication/#authentication_1) on the ceramic docs explains how to make various types of did providers.  If you're trying to use a key-did using `Ed25519Provider`, you'll need to make sure to click `key-did-provider` to change the example code to be specific to that provider type.  There are also examples for using `3id-did-provider` as well as for using `3ID Connect` for browser based authentication to a 3ID DID.

To clarify, you won't use the IDX library directly to instantiate the DID provider or give it to Ceramic.  Rather you create a did provider, give it to your ceramic instance, and then give your ceramic instance to the IDX constructor.  Hope that helps!

**Comment by jeffkhull** [comment]
Thanis @stbrody , this makes sense.  After getting some help from @oed , it seems the issue was that these were placeholders that won't work when running directly:

```js
schema: "ceramic://kyz123...456",
controllers: ["did:3:kyz123...456"],
```

The docs were updated to use this code instead, which works for the quick start.

```js
const doc = await ceramic.createDocument('tile', {
  content: { foo: "bar" },
  metadata: {
    controllers: [ceramic.did.id],
    family: "doc family"
  }
})
```

Thanks again!
