### ISSUE TITLE
Change "sync" DocOpt to an enum

### ISSUE THREAD

**Issue by stbrody** [ceramicnetwork/js-ceramic#1123]
with 3 values.  One that means don't sync the tip from pubsub at all, one that means sync the tip from pubsub only if we didn't previously have any state for this document in the Repository (this is the current behavior of sync:true), and one that means always sync even if we have state for the doc in the Repository (this will be new behavior).

```
enum SyncOptions {
  DONT_SYNC,
  SYNC_ON_LOAD, // Open to ideas for a better name for this.  Maybe just `SYNC` and call the other option `FORCE_SYNC`?
  SYNC_ALWAYS, // or FORCE_SYNC?
}
```

**Comment by oed** [comment]
> and one that means always sync even if we have state for the doc in the Repository (this will be new behavior).

This would only happen on startup I presume? Would be bad if we try to sync it every time we load it from disk (we should still listen to updates for it when it's not loaded).

**Comment by stbrody** [comment]
> > and one that means always sync even if we have state for the doc in the Repository (this will be new behavior).
> 
> This would only happen on startup I presume? Would be bad if we try to sync it every time we load it from disk (we should still listen to updates for it when it's not loaded).

It would be a flag that could be set any time a document is loaded. So no, not just at startup.  But now when a user/application calls loadDocument, they can specify to do no syncing (get whatever contents is already stored in the cache or the state store or get back nothing if there is no state already stored in the Repository), have the current syncing behavior (get the state from the cache or state store, but if there is no existing state then request the tip from pubsub and wait 3 seconds for it), or use the new "force sync" behavior (request the tip from pubsub and wait 3 seconds for a response, even if we already have state stored in the cache or state store for this doc)

I assume the CLI would continue to have the same default behavior as it does today, though we may choose to expose this option via a new cli flag at some point.  Something like `--force-sync`.

**Comment by oed** [comment]
Ok, thanks for clarifying!

**Comment by stbrody** [comment]
As part of this, will also add a new field to `DocOpts` called `syncDelay`.  The value controls the number of milliseconds to wait for a pubsub response when `sync` is true. Default will be 3000, as it is today.
