### ISSUE TITLE
Can't load state of document using CommitID

### ISSUE THREAD

**Issue by oed** [ceramicnetwork/js-ceramic#1134]
**Describe the bug**

The cli command `ceramic state <commitid>` throws an error because it expects a DocID not a CommitID. We should allow for both.

**To Reproduce**
1. Create a document
2. List commits using `ceramic commits <docid>`
3. Try to load one of the commits using `ceramic state`

**Expected behavior**
It should work ;) 

**Screenshots**

**Ceramic versions** 
**@ceramicnetwork/cli@0.21.0-rc.10**

**Machine, OS, browser information (please complete the following information):**
macos

**Comment by ukstv** [comment]
Cc @zachferland
