### ISSUE TITLE
Move 'unique' into GenesisHeader

### ISSUE THREAD

**Issue by stbrody** [ceramicnetwork/js-ceramic#1143]
I'd like to move the 'unique' into [GenesisHeader](https://github.com/ceramicnetwork/js-ceramic/blob/56912f56b74f0b97fdb95df972d6182389b2a7e4/packages/common/src/doctype.ts#L30) and out of [GenesisCommit](https://github.com/ceramicnetwork/js-ceramic/blob/56912f56b74f0b97fdb95df972d6182389b2a7e4/packages/common/src/doctype.ts#L35).  Having `unique` as a third top-level field of `GenesisCommit` complicates some of the code that primarily works with `content` and `metadata` (which map directly to `data` and `header` in `GenesisCommit`). Also, now that we're receiving `deterministic` in `TileMetadata`, it makes even more sense to treat it similarly to other fields of the metadata, just one that only shows up in the genesis commit.

**Comment by stbrody** [comment]
Any objection @oed?

**Comment by oed** [comment]
Should be fine I think

**Comment by stbrody** [comment]
This has been merged and has an effect that is backwards breaking in a limited way.  If there are existing documents that were created with the `deterministic` flag, now creating the document with the same contents using the `deterministic` flag will not resolve to the same DocID as was created in earlier versions.  This means that any updates that were made to a document that was created deterministically will not be discoverable by deterministically recreating the document from the genesis contents.  If you know the original document's DocID, you will still be able to load and use that document normally, and new documents created deterministically from now one will also work as expected. But documents that created deterministically on the new version of Ceramic will not resolve to the same document as if they were created against previous versions of Ceramic.

The place this is most likely to be noticed is for users of IDX.  The IDX index document is loaded by using deterministic document resolution. This means that IDX documents created for a DID on previous versions of Ceramic will not be discoverable for the same DID on the new version of Ceramic, and will need to be re-created.
