### ISSUE TITLE
Change the way metadata is encoded in tile doctype commits

### ISSUE THREAD

**Issue by stbrody** [ceramicnetwork/js-ceramic#1149]
The way `content` and `metadata` are handled within the commit protocol for Tile documents is very different.
For content, each SignedCommit in a Tile document's log will have a `data` field [containing a json-patch](https://github.com/ceramicnetwork/js-ceramic/blob/1790c0bd368fd6857a1e68191a3605616931bea7/packages/doctype-tile-handler/src/tile-doctype-handler.ts#L135) diff between the previous contents and the new contents.  For metadata, each SignedCommit in the document's log contains a `header` field [containing the new values](https://github.com/ceramicnetwork/js-ceramic/blob/1790c0bd368fd6857a1e68191a3605616931bea7/packages/doctype-tile-handler/src/tile-doctype-handler.ts#L136) for fields that were provided by the user when they called `.change()`.  This is weird because it is neither a simple full object replacement stating that this is the new version of the metadata (since unchanged fields are omitted) nor is it a proper diff.  I believe that fields that the user manually specifies when calling `.change()` get encoded into the commit header, even if they are unchanged from the previous version.  This behavior is inconsistent and difficult to reason about.  Also [this merge strategy](https://github.com/ceramicnetwork/js-ceramic/blob/1790c0bd368fd6857a1e68191a3605616931bea7/packages/doctype-tile-handler/src/tile-doctype-handler.ts#L136) for how the new metadata is calculated off of the old metadata and the commit header is a very javascript-centric way of doing it.  I'm not sure this will translate well when we have Tile implementations in other languages.  Also, with this approach there is no way to clear out an existing metadata field (you can explicitly set it to `null` or `undefined`, but you can't remove it from the metadata entirely).

I propose that we start using jsonpatch to encode diffs for the metadata, same as we do for content

**Comment by stbrody** [comment]
@oed LMK what you think

**Comment by oed** [comment]
I'm fine with that as long as it can be done in a way which doesn't break existing document logs.

**Comment by stbrody** [comment]
Right, this would be a breaking change, which is why I want to do it now before mainnet launches.
