### ISSUE TITLE
Error: Failed to resolve did:3kjzl6cw....?version-id=0#tub3u2DCsKPgWEe: invalidDid, Error: Cannot read property 'forEach' of undefined

### ISSUE THREAD

**Issue by Luis-Palacios** [ceramicnetwork/js-ceramic#1155]
**Describe the bug**
Hello, I'm following this guide: https://developers.ceramic.network/build/authentication/ and my code is currently like this:
```js
import CeramicClient from '@ceramicnetwork/http-client'
import { ThreeIdConnect,  EthereumAuthProvider } from '3id-connect'

 const CERAMIC_URL = 'https://ceramic-clay.3boxlabs.com';
 const addresses = await window.ethereum.enable();
 const threeIdConnect = new ThreeIdConnect();

 const authProvider = new EthereumAuthProvider(window.ethereum, addresses[0])
 await threeIdConnect.connect(authProvider)
 const provider = await threeIdConnect.getDidProvider()
 const ceramic = new CeramicClient(CERAMIC_URL);

// @ts-ignore
await ceramic.setDIDProvider(provider)
```
package.json dependencies
```json
"3id-connect": "^1.0.0-alpha.15",
"@ceramicnetwork/http-client": "^0.10.0",
```

On the UI side I can correctly connect my metamask wallet, and then the iframe for did correctly appears:

![image](https://user-images.githubusercontent.com/4844997/112506036-fc9e4e80-8d52-11eb-967e-30bdab29b6d3.png)

Once I click continue

![image](https://user-images.githubusercontent.com/4844997/112506081-06c04d00-8d53-11eb-8d30-15e62454002d.png)

Once I click sign it stays like this for a few seconds

![image](https://user-images.githubusercontent.com/4844997/112506348-45560780-8d53-11eb-9202-20d7466d0e72.png)

and then I get the following error as the title describe:

![image](https://user-images.githubusercontent.com/4844997/112506443-5f8fe580-8d53-11eb-8558-97c653758cd8.png)

Call Stack
```DID.<anonymous>
node_modules/@ceramicnetwork/http-client/node_modules/dids/lib/index.js (153:0)
Generator.next
<anonymous>
fulfilled
/_next/static/chunks/pages/ceramic.js (17329:58)
```

Any ideas what I'm doing wrong?

**Comment by Luis-Palacios** [comment]
Update:

I have noted the POST API Request: https://ceramic-clay.3boxlabs.com/api/v0/multiqueries is returning 500
PayLoad:
```
queries: {
[
  {
    "docId": "kjzl6cwe1jw147in103qjm6wxd5ms8sxxb209jv06minbyxhvqyc6tu5wqbrfcf"
  },
  {
    "docId": "k3y52l7qbv1frxxgjr4qkrht659k20ult8um9vx8hb44lx4e75ro6ok6i0r7n14ao"
  }
]
}
```

![image](https://user-images.githubusercontent.com/4844997/112511573-28700300-8d58-11eb-810d-0dab52a2e3c4.png)

![image](https://user-images.githubusercontent.com/4844997/112511695-45a4d180-8d58-11eb-96c7-f7d0c96af6d5.png)

**Comment by oed** [comment]
Thanks for reporting @Luis-Palacios.

@valmack looks like this is related to the other 500 issues we've been seeing?

**Comment by Luis-Palacios** [comment]
are these 500 issues on the public `https://ceramic-clay.3boxlabs.com` node? or is it on any ceramic node.

I mean will I also run into this kind of issue if I try to use a local ceramic `ceramic daemon` ?

**Comment by stbrody** [comment]
> @oed are these 500 issues on the public `https://ceramic-clay.3boxlabs.com` node? or is it on any ceramic node.
> 
> I mean will I also run into this kind of issue if I try to use a local ceramic `ceramic daemon` ?

While we haven't confirmed the cause of the 500 errors with 100% certainty yet, we are currently suspecting an issue with the load balancer we are running in our hosted infra.  If that is indeed the source of the issue, then running your own local ceramic daemon would not have the same problem

**Comment by valmack** [comment]
Yup exactly as @stbrody said

@Luis-Palacios are you getting these errors consistently or seeing some work and some fail?

**Comment by Luis-Palacios** [comment]
I'm getting errors every time, I tried locally but I also ran into similar issues
```
Error: Failed to resolve did:3:kjzl6cwe1jw147in103qjm6wxd5ms8sxxb209jv06minbyxhvqyc6tu5wqbrfcf?version-id=0#tub3u2DCsKPgWEe: invalidDid, TypeError: Network request failed
```

**Comment by Luis-Palacios** [comment]
I have created a simple repo that desmotrate the issue, at on my machine....

**Comment by Luis-Palacios** [comment]
I'm using node v14.16.0 in case that has something to do

**Comment by oaksprout** [comment]
I'm using `ceramic.multiQuery()` and am getting the same error.

I'm calling it via the http-client and my code looks something like this:

```js
const lensQueries = [
      {
        docId:
          'kjzl6cwe1jw148eyhsz3s8mc0ohl2o7j0b5m02djv7bn4k1m5r2oh8p4ak0ayb1',
      },
    ]

const lenses = await ceramic.multiQuery(lensQueries)
```

Here's the console error:

```console
Error: Cannot read property 'forEach' of undefined
    at Object.fetchJson (utils.ts:18)
    at async CeramicClient.multiQuery (ceramic-http-client.ts:173)
    at async setupLenses (LensSection.tsx:59)
```
