### ISSUE TITLE
Unbundle DIDResolvers from CeramicApi

### ISSUE THREAD

**Issue by oed** [ceramicnetwork/js-ceramic#1159]
Currently both the http-client and core have to explicitly import the DIDResolvers that they support. This is a bit problematic since the 3id-did-resolver and many other possible resolvers depend on the CeramicApi, which causes circular dependencies when using http-client or core in tests. 

One solution to this is to remove the `setDIDProvider` method on CeramicApi and instead accept a DID instance as a required constructor argument. The DID instance can come loaded with the DIDResolvers that the developer wants to use. In order to be able to change the currently authenticated DID we could add a simple setter `ceramic.did = newDid`.

**Comment by oed** [comment]
@stbrody could you perhaps pick this up as part of your API epic? Would be nice to not introduce this as a breaking change later!

**Comment by stbrody** [comment]
> The DID instance can come loaded with the DIDResolvers 

Are there changes to the [js-did](https://github.com/ceramicnetwork/js-did) package that would be needed to support this?  Or does the DID instance already have functionality to provide multiple DIDResolvers to it?

**Comment by oed** [comment]
@stbrody no changes should be needed to js-did!

**Comment by oed** [comment]
Another alternative is to do something like this:

```js
const ceramic = new Ceramic()
const did = new DID({ resolver: ThreeIdResolver.getResolver(ceramic), provider })

await ceramic.setDID(did) // This would authenticate if not already authenticated
```

I think introducing a new concept like "Ceramic transport" would be quite a large refactor (I don't know exactly what it would mean).

**Comment by PaulLeCam** [comment]
I think the fundamental problem is that `3id-did-resolver` has a dependency on `http-client` and `http-client` a dependency on `3id-did-resolver`, no?
So the idea if having a "transport" package is that `3id-did-resolver` would have dependency on this `transport` package, and `http-client` could have dependency on both the `transport` and `3id-did-resolver` packages without having a circular dependency.

**Comment by oed** [comment]
I don't understand how a `transport` package could work. Could you elaborate?

Note that `nft-did-resolver` and likely other DID resolvers will also depend on Ceramic in the future.

**Comment by PaulLeCam** [comment]
Sure, basically the difference I see is that the transport package only cares about networking (HTTP requests for the HTTP client and IPFS interactions for the core client), then the actual "Ceramic client" on top takes care of signing the commits and pushing the signed data to the transport.
This way the transport doesn't need to care about DIDs, so it can be used by dependencies of the DID or related packages such as the resolvers.

**Comment by oed** [comment]
That's not right. The "transport" (what is now `CeramicApi`) needs to use the DID instance with resolvers to verify signatures.

**Comment by oed** [comment]
It would work for the http client I guess, but would not for the core implementation.

**Comment by oed** [comment]
The benefit here is that anyone could provide resolvers to ceramic to add support for new DID methods.

**Comment by stbrody** [comment]
> Another alternative is to do something like this:
> 
> ```js
> const ceramic = new Ceramic()
> const did = new DID({ resolver: ThreeIdResolver.getResolver(ceramic), provider })
> 
> await ceramic.setDID(did) // This would authenticate if not already authenticated
> ```

How is that different from what we have today with `ceramic.setDIDProvider` from the perspective of the circular dependency/initialization order problem?

**Comment by oed** [comment]
> How is that different from what we have today with ceramic.setDIDProvider from the perspective of the circular dependency/initialization order problem?

The both ceramic core and http-client would no longer depend on `3id-did-resolver` which has devDeps on http-client.

**Comment by oed** [comment]
Yep, you are exactly right @stbrody

**Comment by stbrody** [comment]
Heads up this might become a blocker to the rest of my API cleanup work because of [this weird compiler error](https://github.com/ceramicnetwork/js-ceramic/pull/1180#discussion_r604348910) so would be nice to reach consensus on an approach forward soon if possible

**Comment by stbrody** [comment]
As best I can tell the idea of making setting the resolver happen after Ceramic construction is the best bet, probably by providing a DID instance with the resolver set.  Basically what Joel showed in [this comment](https://github.com/ceramicnetwork/js-ceramic/issues/1159#issuecomment-811801301).  @PaulLeCam does that make sense to you?  Or do you still have concerns about that approach?

**Comment by PaulLeCam** [comment]
I think that can work, as long as we can avoid the circular dependencies (including being circular because of dev dependencies needed for tests).
Then we need to make sure the docs are updated accordingly, as we're pushing the complexity of creating the DID instance up to the user we need to make sure it's well understood.

**Comment by oed** [comment]
Yeah, docs need to be updated anyway with all of the breaking API changes that we are introducing in the API refactor release.

**Comment by stbrody** [comment]
Does this cause a problem if you want to use Ceramic in a read-only mode?  It seems like today you could use Ceramic to load documents without needing to be authenticated as any DID at all, and the internal resolvers could still be used to verify the documents being loaded.  Now we're forcing users to provide a specific DID instance that they can authenticate to and use to sign messages, even if they aren't intending on actually authoring any new commits.  Is that a problem?  @oed

**Comment by oed** [comment]
@stbrody it shouldn't cause any issues. You can create a DID instance without any did-provider, just did-resolvers. We need to be careful about where / when we call `authenticate()` though!
@stbrody
