### ISSUE TITLE
Eliminate os and path requirements from common

### ISSUE THREAD

**Issue by ukstv** [ceramicnetwork/js-ceramic#1160]
Currently https://github.com/ceramicnetwork/js-ceramic/blob/develop/packages/common/src/logger-provider.ts requires `os` and `path`, which are Node.js-specific. Common should not depend on Node.js-specific dependencies.

**Comment by stbrody** [comment]
This is one of the issues preventing building with webpack, as captured in https://github.com/ceramicnetwork/js-ceramic/issues/1163
