### ISSUE TITLE
CAIP10 Link Docs works with all blockchains in blockchain utils 

### ISSUE THREAD

**Issue by zachferland** [ceramicnetwork/js-ceramic#1175]
works/tested with ethereum, but other blockchains passing tests in blockchain utils failed when link proofs actually added to docs 

no sure if the status of this is the same, or if has been fixed since then

**Comment by oed** [comment]
Duplicate, closing

**Comment by stbrody** [comment]
Closed in favor of https://github.com/ceramicnetwork/js-ceramic/issues/1232
