### ISSUE TITLE
Rename 'content' to 'did' in Caip10Link

### ISSUE THREAD

**Issue by stbrody** [ceramicnetwork/js-ceramic#1207]
This may require some bigger refactorings of the `Doctype` and `DocState` interfaces.  There are several places in our code that assume that all doctypes have `content`

**Comment by stbrody** [comment]
I wonder how far it makes sense to take this right now... Really the only fields from [DocState](https://github.com/ceramicnetwork/js-ceramic/blob/6bc0da66fe4ebc109b5a810b1b36309640a552b7/packages/common/src/doctype.ts#L102-L112) that are guaranteed to be in all doctypes are `doctype` and `log`.  Although even that it isn't a given that `log` will always be a simple array...

**Comment by oed** [comment]
Can't we just keep it in the `content` property of the DocState, but expose it as a `did` property on the api?

**Comment by stbrody** [comment]
> Can't we just keep it in the `content` property of the DocState, but expose it as a `did` property on the api?

We could *add* `did` as an alias to `content` pretty easily, but we can't *replace* `content` with `did` without first breaking the assumption that **all** doctypes have `content`

**Comment by oed** [comment]
That's not what I mean. I mean just expose a `did` property on the *Caip10Link* class!

**Comment by stbrody** [comment]
> That's not what I mean. I mean just expose a `did` property on the _Caip10Link_ class!

That's what I meant by adding `did` as an alias to `content`. We can add a `did` property to `Caip10Link`, but that won't remove the `content` property it inherits from `Doctype`

**Comment by stbrody** [comment]
OH!  I see, we can remove the `content` property from `doctype` without removing it from `DocState`.  I get it now.  Yes I think that would work well
