### ISSUE TITLE
Http-client should expose DocOpts to loadDocument

### ISSUE THREAD

**Issue by stbrody** [ceramicnetwork/js-ceramic#1220]
[CeramicClient.loadDocument](https://github.com/ceramicnetwork/js-ceramic/blob/f594ff081048f0966c4dc8a57a3952e4235639f8/packages/http-client/src/ceramic-http-client.ts#L128) does not accept a docOpts argument. This is in violation of the [CeramicApi](https://github.com/ceramicnetwork/js-ceramic/blob/f594ff081048f0966c4dc8a57a3952e4235639f8/packages/common/src/ceramic-api.ts#L80) that it is supposed to be implementing.

**Comment by stbrody** [comment]
Fixing this isn't as trivial as it seems at first glance, because `loadDocument` works by making a [GET request to the 'documents' endpoint](https://github.com/ceramicnetwork/js-ceramic/blob/f594ff081048f0966c4dc8a57a3952e4235639f8/packages/http-client/src/document.ts#L71). GET requests don't allow a body, which makes it difficult to add additional JSON arguments to the invocation.

It seems our options are either to switch to a POST request, or serialize the DocOpts to a string in a format that is URL-safe and encode it into the URL that we make the GET request to.  @oed @ukstv, thoughts on which is better?  If the latter, do you know if there's a library that can do that encoding from a javascript object to a URL-safe string with all the proper escaping and everything (and decode it on the other end)?

**Comment by ukstv** [comment]
https://www.npmjs.com/package/queryparams @stbrody

**Comment by stbrody** [comment]
> [npmjs.com/package/queryparams](https://www.npmjs.com/package/queryparams) @stbrody

That package seemed to do a bit more than what we need, and seemed to have some assumptions of being run in browser (see [this test](https://github.com/dzucconi/queryparams/blob/master/src/configure.test.ts#L34) which shows that the library expects to be able to interfere with the browser's search bar.  I wound up going with https://www.npmjs.com/package/queryparams, which seems simply and allows just converting an object to the query string
