### ISSUE TITLE
Add streamtype to DocState

### ISSUE THREAD

**Issue by stbrody** [ceramicnetwork/js-ceramic#1240]
The [DocState interface](https://github.com/ceramicnetwork/js-ceramic/blob/ce0694b8405f29a6c54a2d214599d210e6f1e4de/packages/common/src/doctype.ts#L103-L113) currently has a "doctype" field that is a string.  We should change that to a "streamtype" field that is a number for the streamtype ID rather than the streamtype name, to be resilient to possible future renames of a doctype.

For now we will keep the existing `doctype` field around as-is, for backwards compatibility since it is exposed via the http API, but we will mark it deprecated and remove it in a future version

**Comment by oed** [comment]
Sounds good. Instead of adding a `streamtype` add just a new property `type` which contains the number.
