### ISSUE TITLE
Program is crashing in production only w/ invalidDid

### ISSUE THREAD

**Issue by dysbulic** [ceramicnetwork/js-ceramic#1251]
**Bug Description**

When the button is clicked on https://dysbulic.github.io/xml-to-ipld/#/ceramic the application crashes with the following error:

```
Uncaught (in promise) Error: Failed to resolve did:3:kjzl6cwe1jw14936apxr6lxhewn3srcpxjwjtu777mkfio7718ue8alc7pfr717?version-id=0#pn1iiYhhzD3kUev: invalidDid, TypeError: Cannot call a class as a function
    at A.<anonymous> (index.ts:303)
    at c (runtime.js:63)
```

The value of `DID` before the error is:

![Screenshot from 2021-04-14 01-49-05](https://user-images.githubusercontent.com/181523/114660696-be49de80-9cc3-11eb-8d75-c2dc0279cac5.png)

This issue *does not* occur in development. In development, the value of `DID` at the same location is: 

![Screenshot from 2021-04-14 01-49-41](https://user-images.githubusercontent.com/181523/114660733-d0c41800-9cc3-11eb-9840-26000615a7fd.png)

The code being run is:

```javascript
  const connect = async () => {
    ⋮
    const ceramic = (
      new Ceramic('https://ceramic-clay.3boxlabs.com')
    )
    await ceramic.setDIDProvider(didProvider)
    setCeramic(ceramic)
  }
```

Then in `@ceramicnetwork/http-client`:

```javascript
  async setDIDProvider(provider: DIDProvider): Promise<void> {
    this.context.provider = provider;
    this.context.did = new DID({ provider, resolver: this.context.resolver })
    if (!this.context.did.authenticated) {
      await this.context.did.authenticate()
    }
  }
```
It dies calling `new DID()`.

**To Reproduce**

1. Go to https://dysbulic.github.io/xml-to-ipld/#/ceramic.
2. Click on the "Connect Your Wallet" button.
3. View the error in the console.
4. `git clone https://github.com/dysbulic/xml-to-ipld.git`
5. `cd xml-to-ipld && yarn && yarn start`
6. No error and the program completes satisfactorily.

**Expected Behavior**

I would like the behavior in production to be the same as development.

**Ceramic Versions** 

* `@ceramicnetwork/3id-did-resolver@^1.1.1`
* `@ceramicnetwork/common@^0.17.0`
* `@ceramicnetwork/docid@^0.5.1`
* `@ceramicnetwork/doctype-caip10-link@^0.13.4`
* `@ceramicnetwork/doctype-tile@^0.14.1`
* `@ceramicnetwork/http-client@^0.10.1`
* `@ceramicstudio/idx@^0.7.0`
* `@ceramicstudio/idx-tools@0.9.0`

**Machine, OS, Browser Information**

* `Linux fenrir 5.8.0-48-generic #54~20.04.1-Ubuntu SMP Sat Mar 20 13:40:25 UTC 2021 x86_64 GNU/Linux`
* Browsers:
  * Chrome 89.0: Works in development, not in production.
  * Firefox 87.0: Works in development, not in production.
  * Opera: Crashes b/c `accounts[0]` is not defined.
  * Brave: Crashes b/c `window.ethereum` is not defined.

**Additional Information**

It looks to me like the minimizer made a mistake, but that just seems so unlikely.

**Comment by oed** [comment]
That's quite strange. What's the difference between your production and your develop environments?

**Comment by dysbulic** [comment]
> What's the difference between your production and your develop environments?

Now that you mention it, I was trying to use [loadable components](//loadable-components.com) and webpack to do authorized cross-site scripting.

I'm pretty sure something I did there has borked webpack. I'll investigate.

Thanks.

**Comment by Geo25rey** [comment]
@dysbulic Did you every figure this out? I am having a similar problem using create-react-app.

**Comment by dysbulic** [comment]
@Geo25rey, I've not yet figured it out. I tried pulling out everything custom I did to Webpack, removing `node_modules/` (then `yarn.lock`), and now I'm getting an error that `TextDecoder` is not defined. It should be built in to the browser.

I've honestly not been working on it much because it works locally, so I can run my tests. I just can't share them w/ anyone.

**Comment by Geo25rey** [comment]
> @Geo25rey, I've not yet figured it out. I tried pulling out everything custom I did to Webpack, removing `node_modules/` (then `yarn.lock`), and now I'm getting an error that `TextDecoder` is not defined. It should be built in to the browser.

Run `npm install --save --exact-version web-encoding@1.0.6`, I had the same issue recently.

**Comment by Geo25rey** [comment]
@dysbulic Check [this](https://github.com/ceramicnetwork/js-ceramic/issues/1311#issuecomment-825254035) out
