### ISSUE TITLE
Update DIDs packages

### ISSUE THREAD

**Issue by valmack** [ceramicnetwork/js-ceramic#1304]
Packages that need an update, re: @PaulLeCam 
> - dids (pushed new version this morning)
> - key-did-provider-ed25519 (PR linked above)
> - 3id-did-provider
> - ceramic common I guess (if it needs the type for the DID provider)
> - any other ceramic package using the DID provider type

**Comment by valmack** [comment]
Depends on https://github.com/ceramicnetwork/key-did-provider-ed25519/pull/3

**Comment by stbrody** [comment]
@valmack, what's the state of this ticket?  Is this still an issue?

**Comment by ukstv** [comment]
Nope @stbrody 3id-did-provider is the only remaining thing here, and it's on me.

**Comment by oed** [comment]
This can be closed as it's about updating `dids` to v2.
