### ISSUE TITLE
Slow IDX interactions on clay infra

### ISSUE THREAD

**Issue by oed** [ceramicnetwork/js-ceramic#1312]
**Describe the bug**
Reported by the Torus team. The clay infra nodes are quite slow compared to a local ceramic cli node which is much faster. 

Not sure if this could be a bug in ceramic or some issue with our configuration of the clay infra.

**To Reproduce**

```js
const connect = async()=>{
    await ceramic.setDIDProvider(provider)
    idx = new IDX({ ceramic })
};

const read = async()=>{
    const profile = await idx.get('basicProfile')
    console.log("my profile", profile);
}

const write = async()=>{
    await idx.set('basicProfile', {
        name: 'Him timdddd',
        description: 'I make.',
        emoji: '💻',
    })
}

(async()=>{
    console.time("connectTime");
    await connect();
    console.timeEnd("connectTime");
    console.time("writeTime");
    await write();
    console.timeEnd("writeTime");
    console.time("readTime");

    await read();
    console.timeEnd("readTime");
    return null
})();
```
```
output: connectTime: 22.979ms
writeTime: 10.814s
my profile { name: 'Him timdddd', description: 'I make.', emoji: '💻' }
readTime: 2.213s
```
These results are from using `https://ceramic-clay.3boxlabs.com`
However, with ceramic daemon it is quite fast.

**Expected behavior**
We should get roughly the same speed at both clay infra and a local node.

**Comment by oed** [comment]
@PaulLeCam tagged you here as well. Wondering if there might be some inefficiencies in how js-idx is implemented perhaps. Weird that it would behave differently on a local node however.

**Comment by ukstv** [comment]
Noticed something similar yesterday when playing with AWS backend yesterday. To me it seemed like a slow requests to AWS backend.

**Comment by oed** [comment]
Ok, seems worthwhile to investigate then. Not good if we see the same on our mainnet nodes when ELP starts.
cc @valmack
