### ISSUE TITLE
Too many file descriptors on CAS clay

### ISSUE THREAD

**Issue by valmack** [ceramicnetwork/js-ceramic#1314]

**Comment by stbrody** [comment]
Now that https://github.com/ceramicnetwork/ceramic-anchor-service/issues/393 is in, I think the simplest fix for this is to up the max file descriptor ulimit on the CAS machine to be twice the number of streams that can be anchored in a batch (as derived from the merkleDepthLimit)

**Comment by stbrody** [comment]
Taking myself off this ticket and adding Val as the fix now lives infra-side

**Comment by valmack** [comment]
Closing this because we have a ticket filed here: https://github.com/3box/ceramic-infra/issues/303 and this is the wrong repo for this anyway.
