### ISSUE TITLE
MultiQueries won't work for streamtypes without a `content` property

### ISSUE THREAD

**Issue by stbrody** [ceramicnetwork/js-ceramic#1340]
The [implementation of multiqueries](https://github.com/ceramicnetwork/js-ceramic/blob/967cf11ec95e5cd6650bfa49fa1efd9adab85d1b/packages/core/src/ceramic.ts#L523) expects the stream to have a `content` property, but we've made the properties available on each Stream be StreamType specific.  This should probably work by inspecting the `content` of the `StreamState` directly: https://github.com/ceramicnetwork/js-ceramic/blob/64192b3adec20d40f2f2427aee80226387cb35ef/packages/common/src/stream.ts#L106

**Comment by oed** [comment]
I imagine that the Stream interface should have some method to check paths in the future so we don't have to rely on internals like StreamState here.
