### ISSUE TITLE
TileDocument.create should error if 'deterministic' is true and content is provided

### ISSUE THREAD

**Issue by stbrody** [ceramicnetwork/js-ceramic#1343]
If content is provided in a genesis commit then the genesis commit gets signed, which prevents deterministic document lookup from anyone other than document's controller. To prevent users from accidentally shooting themselves in the foot, we should prevent this from happening.

**Comment by stbrody** [comment]
One could make the case that we should still allow this since deterministic document lookup with content would still be possible by the document controller (so long as the controller's signing key hasn't been rotated since the document was created).  But that seems like an edge case with enough nuance and complexity to use correctly that it probably isn't worth supporting.  @oed do you agree?

**Comment by oed** [comment]
Don't have a strong sense here. Don't think this feature is important.

**Comment by smrz2001** [comment]
I didn't quite grok the final conclusion here. We still want to block genesis commits from getting signed?

**Comment by oed** [comment]
* If `deterministic` flag is present in metadata:
  * If `content` is empty don't sign the genesis commit
  * If `content` has data, throw error
* Else:
  * Always sign genesis commit

**Comment by smrz2001** [comment]
For the else-block (`deterministic` is `false`), we should always sign the genesis commit? Or only when there is content? Existing behavior is to not sign in the absence of content.

**Comment by oed** [comment]
Eh, I'm not sure it really matters at all tbh. Any thoughts @stbrody ?

**Comment by stbrody** [comment]
> Eh, I'm not sure it really matters at all tbh. Any thoughts @stbrody ?

I feel similarly indifferent.  There's not much difference between an empty stream without a signature and an empty stream where the creator has attested to their creation of the empty stream

**Comment by smrz2001** [comment]
Ok, gotcha, thanks both 👍🏼

**Comment by smrz2001** [comment]
After playing with the tests, I'm realizing that a bunch of them create genesis records with data and `deterministic = true` in order to deterministically match the saved snapshots.

Throwing an error when data is present and `deterministic = true` at document creation would mean changing these tests to either not be able to validate the records deterministically or to not specify data in the commits, which would make the comparisons trivial and probably not useful.

Does that make sense?

**Comment by stbrody** [comment]
I think we should probably just fix the tests.  If the tests need to create multiple deterministic documents with different streamids you can set different tags and/or family in the metadata

**Comment by smrz2001** [comment]
Cool, will try that 👍🏼

**Comment by smrz2001** [comment]
cc @ukstv since he wrote most (all?) of the TileDocument tests and might also have an opinion.

**Comment by ukstv** [comment]
Thanks @smrz2001 for the ping. I agree with @stbrody that the current behaviour leads to mass feet-shooting. I do see, that deterministic StreamID generation based on some information is important. In our case it could be put as metadata or content. Most probably maybe (I am not really sure) deterministic tiles link something together, so this kind of information belongs to metadata. +1 to suggestion. This does not prevent from extending later to some other option like `doNotSign` that would make deterministic StreamID based on content also.

**Comment by stbrody** [comment]
Longer term I also think https://github.com/ceramicnetwork/js-ceramic/issues/1342 will be very valuable in expanding the usefulness of deterministic document queries, without requiring deterministic documents with non-null content
