### ISSUE TITLE
Dispatcher's outstandingQueries set should time out entries after a minute

### ISSUE THREAD

**Issue by stbrody** [ceramicnetwork/js-ceramic#1349]
Currently queries are deleted from the outstandingQuery set after we process a single response: https://github.com/ceramicnetwork/js-ceramic/blob/64192b3adec20d40f2f2427aee80226387cb35ef/packages/core/src/dispatcher.ts#L201

Since we might get multiple responses to a query from different nodes, some of which may have newer/better values than early received responses, we should keep processing expected responses to known queries for more than just the first response.  However, we don't want that set to grow unbounded forever either.  So instead we should include a timestamp whenever a queryId is added to the set, and we should have a background job that runs once a minute and clears out old entries from the set.  This would allow nodes to continue processing query responses for 1 minute after any query they send.  This is useful for keeping the stream state up to date in-memory and in the state store, even after the API call that was waiting to load the stream has returned to the application.

**Comment by smrz2001** [comment]
Is a background task necessary or can we make the cleanup event-driven? By event-driven, I mean that the query set gets cleaned up every time there is an update made to the set. That way we don't add another background task and just amortize the cleanup time across multiple updates to the set.

**Comment by stbrody** [comment]
> Is a background task necessary or can we make the cleanup event-driven? By event-driven, I mean that the query set gets cleaned up every time there is an update made to the set. That way we don't add another background task and just amortize the cleanup time across multiple updates to the set.

Yep, I think that would be fine. Goal is just to make sure that the size of the set doesn't grow unbounded.
