### ISSUE TITLE
Allow both null and undefined as content in TileDocument API

### ISSUE THREAD

**Issue by ukstv** [ceramicnetwork/js-ceramic#1350]
Largely, `null` and `undefined` are used interchangeably. TileDocument only compares to `null` for content as a special case, assuming typecasting.

See https://github.com/ceramicnetwork/js-ceramic/blob/develop/packages/stream-tile/src/tile-document.ts#L270

**Comment by ukstv** [comment]
Moreover, the function signature declares `undefined` to be a valid input.

**Comment by ukstv** [comment]
Solved in https://github.com/ceramicnetwork/js-ceramic/pull/1352

**Comment by stbrody** [comment]
Reopening to leave in 'staging' until released

**Comment by ukstv** [comment]
Ugh, I though the PR went into staging so that this one can be safely closed. Thank you!
