### ISSUE TITLE
Support Ceramic on Node v12

### ISSUE THREAD

**Issue by vaultec81** [ceramicnetwork/js-ceramic#1372]
**Describe the bug**
Cannot run any ceramic commands when running the latest version of ceramic cli on node `v12`.

**To Reproduce**
1. Ensure you are running node `v12`
2. Run `npm install -g @ceramicnetwork/cli` in command line
3. Run `ceramic` command
4. Error should be present in console

**Expected behavior**
The above command should function without error.

**Ceramic versions** 
`@ceramicnetwork/cli`: `1.0.0`

**Machine, OS, browser information**
Issue occurs on both Linux and Windows.

**Additional context**
Issue occurs when using node `v12`

Console output
```
C:\Users\user\AppData\Roaming\npm\node_modules\@ceramicnetwork\cli\node_modules\did-jwt\lib\index.js:1

<Snip snip giant string printed here of likely the webpack contents of `did-jwt\lib\index.js:1` above>


SyntaxError: Unexpected token '.'
←[90m    at wrapSafe (internal/modules/cjs/loader.js:1054:16)←[39m
←[90m    at Module._compile (internal/modules/cjs/loader.js:1102:27)←[39m
←[90m    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)←[39m
←[90m    at Module.load (internal/modules/cjs/loader.js:986:32)←[39m
←[90m    at Function.Module._load (internal/modules/cjs/loader.js:879:14)←[39m
←[90m    at Module.require (internal/modules/cjs/loader.js:1026:19)←[39m
←[90m    at require (internal/modules/cjs/helpers.js:72:18)←[39m
    at Object.<anonymous> (C:\Users\user\AppData\Roaming\npm\node_modules\←[4m@ceramicnetwork←[24m\cli\node_modules\←[4mkey-did-provider-ed25519←[24m\dist\key-did-provider-ed25519.cjs.development.js:8:14)
←[90m    at Module._compile (internal/modules/cjs/loader.js:1138:30)←[39m
←[90m    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)←[39m
```

**Resolution:** 
Issue was fixed for me by installing v14, however, for some this might not be as straight forward.

**Comment by stbrody** [comment]
We have no current plans to support node v12
