### ISSUE TITLE
Feature Request: Add interface to set the DID of a Caip10Link document to null

### ISSUE THREAD

**Issue by Geo25rey** [ceramicnetwork/js-ceramic#1409]
I am looking for a way to remove the link created using `Caip10Link` to a DID. I tried to use `Caip10Link.setDid()` with the DID set to `null` and `{}`. Neither of these had any side effects to the `Caip10Link` document.

I propose a new interface, `Caip10Link.clearDid(authProvider: AuthProvider, opts?: UpdateOpts)`, which will set the DID field in the `Caip10Link` document to `null` as it's originally set.

Thanks @stbrody for informing me that this isn't supported (yet).

**Comment by stbrody** [comment]
@Geo25rey, can you let us know how critical this is to you so we can prioritize it alongside our other pressing work?  Is this blocking your ability to develop on Ceramic?

**Comment by Geo25rey** [comment]
@stbrody It will probably not be an explicit blocker for the next ~1-2 weeks, but it is not great from a user privacy perspective and it hurts the reliablity of mapping crypto wallets to DIDs.

**Comment by stbrody** [comment]
@oed, do you think this is something @smrz2001 could pick up next sprint?

**Comment by oed** [comment]
Sure, should be simple to add to the blockchain-util package.

**Comment by Geo25rey** [comment]
Wouldn't it be as simple as copying the `Caip10Link.setDid()` method and passing in the value `null` to `createLink()` for the DID string?

**Comment by Geo25rey** [comment]
Another idea would be to just set the link proof in the Caip10 document to `null`

**Comment by Geo25rey** [comment]
Any updates? @stbrody @smrz2001

**Comment by smrz2001** [comment]
> Any updates? @stbrody @smrz2001

Apologies for the delay on this, @Geo25rey. We haven't forgotten, just been head-down with ELP this week.

🤞🏼🤞🏼 that next week is way less crazy and we can prioritize this. Thanks so much for your patience.

**Comment by Geo25rey** [comment]
> Apologies for the delay on this, @Geo25rey. We haven't forgotten, just been head-down with ELP this week.
> 
> 🤞🏼🤞🏼 that next week is way less crazy and we can prioritize this. Thanks so much for your patience.

Thanks for the update @smrz2001

**Comment by Geo25rey** [comment]
@smrz2001 How's it going?

**Comment by oed** [comment]
Hey @Geo25rey this is not something that's at the top of our priority list. We will get to it at some point, but could be a while. If you really need this feature PRs are very welcome :)
