### ISSUE TITLE
Loading vanilla commit id fails on https://ceramic-clay.3boxlabs.com

### ISSUE THREAD

**Issue by ukstv** [ceramicnetwork/js-ceramic#1413]
We have a stream `kjzl6cwe1jw14ah67yenpwzapd5jxb8n1umxb7ezabpuk3arw00r6q4gs55emjk`. It contains just one entry - genesis one. Its initial commit is `k3y52l7qbv1fryii48ko8oaj04djhovxfx5v0voqixfbtavgmbk5dbtrrc4mg0b28`. Doing `curl https://ceramic-clay.3boxlabs.com/api/v0/streams/kjzl6cwe1jw14ah67yenpwzapd5jxb8n1umxb7ezabpuk3arw00r6q4gs55emjk` and `curl https://ceramic-clay.3boxlabs.com/api/v0/streams/k3y52l7qbv1fryii48ko8oaj04djhovxfx5v0voqixfbtavgmbk5dbtrrc4mg0b28` should return the same result.

Actually, the latter fails.

**Comment by stbrody** [comment]
Can reproduce.  Also confirmed that loading the CommitID does work on the CLI, it's just on that http endpoint that it fails.

Also can load the commitID via the gateway at https://gateway-clay.ceramic.network/api/v0/streams/k3y52l7qbv1fryii48ko8oaj04djhovxfx5v0voqixfbtavgmbk5dbtrrc4mg0b28 and that also works

**Comment by stbrody** [comment]
I suspect this is the same as the other timeouts I am seeing connecting to `ceramic-clay.3boxlabs.com` @v-stickykeys @oed
