### ISSUE TITLE
Ceramic should track whether pinned streams have been synced and only sync on demand

### ISSUE THREAD

**Issue by stbrody** [ceramicnetwork/js-ceramic#1414]
Currently at startup Ceramic loads all pinned streams and queries pubsub for any updates that might have been missed while the node was offline.  That creates a lot of load on the pubsub network unnecessarily every time a node is restarted.  Instead, Ceramic should track whether each stream in memory is also pinned, and for pinned streams we should track all pinned streams that have been sync'd for the lifetime of this process.  Then when a stream is loaded, the default behavior for pinned streams should be to sync streams only if they haven't already been synced at least once during the lifetime of this process

**Comment by stbrody** [comment]
Some questions:
* Should we change the behavior of the PREFER_CACHE sync mode to this new behavior, introduce a new sync mode (and make it the default), or change the behavior AND rename PREFER_CACHE while keeping its same code?
* This change lets us stop querying pubsub for all pinned streams at startup, but we still have to load all pinned streams so we kick off the process to poll the CAS for any pending anchors.  Is that enough, or do we also need to change that behavior so that we don't need to load all pinned streams at all on startup?

**Comment by stbrody** [comment]
@oed to weigh in on the questions above

**Comment by stbrody** [comment]
I think the behavior is probably similar enough to the existing behavior of PREFER_CACHE that we can probably get away with changing the behavior but leaving it with the same name

**Comment by stbrody** [comment]
I have a few ideas on how to implement this.

1. 
    1. RunningState keeps track of whether or not it was constructed from state that was loaded from the state store
    2. State manager keeps track of a Set of StreamIDs for all pinned streams that have ever been sync'd for the lifetime of the process
    3. When loading a stream and processing the `sync` behaviors, if the RunningState says its from the state store:
        1. it's not in the Set from step ii, then query pubsub and sync the stream
        2. If it is in the Set from step ii, just return the state without syncing
2.
    1. Track in StreamState when the last time the stream was synced, for all streams. This timestamp gets stored in the stream state that gets written to the state store
    2. Keep track of the timestamp when the process starts
    3. When loading a stream, for streams found in the Repository (cache or state store), if the `lastSynced` time is earlier than when the process was started, sync it, otherwise don't
3.
    1. Keep track in persistent storage an incrementing number for how many times this node has been started up.  Call this the *node epoch*.
    2. Track in the StreamState the last *node epoch* in which the stream was synced
    3. When loading a stream, for streams found in the Repository (cache or state store), if the `node epoch` of the last time the stream was synced is lower than the current *node epoch* of the process, sync it, otherwise don't

***Pros/cons of each approach***


**Approach 1**
Pros:
* Doesn't add any extra information into the StreamState, which may be user visible in some cases
Cons:
* The set of StreamIds of pinned-and-synced streams grows unbounded for the lifetime of the process.

**Approach 2**
Pros:
* No unbounded memory growth
* code is less special-cased for the state store, `lastSynced` concept is more general purpose and could possibly be useful in the future.
Cons:
* Relies on the system clock. If the clock on the host machine is changed ever, this behavior can get messed up

**Approach 3**
Pros:
* No reliance on system clock or unbounded memory growth
Cons:
* Requires a place to persistently store the node epoch, which doesn't exist right node.
* Concept of *node epoch* showing up in StreamState may be weird and confusing to users.


***Conclusions***

The reliance on the system clock for approach 2 feels like a dealbreaker.
The combination of the need to add a new mechanism for persistent storage plus the addition of a strange concept (node epoch) in user-visible places makes me feel like approach 3 isn't great either.

That leaves approach 1.  The main downside is the set that grows unbounded for the lifetime of the process, but I'm not actually *too* worried about that.  The data in the set (the StreamID) is fairly small, and the size of the set will only grow as much as the number pinned streams that are queried for the lifetime of the process.  If the size of this set becomes a problem in the future, we could always add a garbage collection mechanism to it, and the only downside is that we might wind up syncing a stream that we have already synced.

I plan to process with approach 1 for now, although @oed @ukstv @smrz2001, please take a look and let me know if you have other ideas or disagree with any parts of my analysis here.

**Comment by oed** [comment]
Could we perhaps store the information as metadata in the state store? 
A per instance property which includes instance number (which is incremented on each time the process starts) and a boolean for each stream.

Haven't thought this though much though, may be flaws with this approach.

**Comment by stbrody** [comment]
> Could we perhaps store the information as metadata in the state store?
> A per instance property which includes instance number (which is incremented on each time the process starts) and a boolean for each stream.
> 
> Haven't thought this though much though, may be flaws with this approach.

Yes, I think if we were to go with approach 3 the state store would be the place to put it.

In any case https://github.com/ceramicnetwork/js-ceramic/pull/1417 is already merged which is an implementation of approach 1
