### ISSUE TITLE
TileDocument.deterministic() API

### ISSUE THREAD

**Issue by PaulLeCam** [ceramicnetwork/js-ceramic#1415]
Using the `deterministic` flag makes APIs a bit strange as the `content` argument must not be defined, and accessing deterministic documents is not really a "create" operation, so I'd suggest to:
- Deprecate the `deterministic` flag in `TileMetadataArgs` (assuming this type is only used for API consumers)
- Add a `TileDocument.deterministic(metadata: TileMetadataArgs): Promise<TileDocument>` static method.
- Maybe enforce that either `family` and/or `tags` are set in the `metadata` (making more explicit what the determinism is based on)

**Comment by stbrody** [comment]
I like this idea
