### ISSUE TITLE
Optimize commit application to minimize calls to IPFS

### ISSUE THREAD

**Issue by stbrody** [ceramicnetwork/js-ceramic#1421]
To see the issue, add this test to `state-manager.test.ts`:
```
test('handleTip for commit already in log', async () => {
  const newContent = {foo: 'bar'}
  const stream1 = await TileDocument.create<any>(ceramic, INITIAL_CONTENT, null, { anchor:false });
  await stream1.update(newContent, null, { anchor: false })

  const ceramic2 = await createCeramic(ipfs);
  const retrieveCommitSpy = jest.spyOn(ceramic2.dispatcher, 'retrieveCommit');

  const stream2 = await ceramic2.loadStream<TileDocument>(stream1.id, { syncTimeoutSeconds:0 });
  const streamState2 = await ceramic2.repository.load(stream2.id, {});


  retrieveCommitSpy.mockClear()
  await (ceramic2.repository.stateManager as any)._handleTip(streamState2, stream1.state.log[1].cid);

  expect(streamState2.state).toEqual(stream1.state);
  expect(retrieveCommitSpy).toBeCalledTimes(2) // actually is 7

  // Now re-apply the same commit and don't expect any additional calls to IPFS
  await (ceramic2.repository.stateManager as any)._handleTip(streamState2, stream1.state.log[1].cid);
  expect(retrieveCommitSpy).toBeCalledTimes(2) // actually is 8

  await ceramic2.close();
});
```

Notice how applying a single SignedCommit results in 7 calls to `ipfs.dag.get`.  I believe this should really only be 2 - one for the base signed commit and one for the dag-jose payload from the `link` commit.  But there are many inefficiencies in the codepaths for applying commits that results in the same CID being loaded multiple times.

**Comment by stbrody** [comment]
FYI @ukstv since this seems relevant to some of the perf issues you've been investigating

**Comment by ukstv** [comment]
Closing in favour of actionable #1444

**Comment by stbrody** [comment]
I'd like to leave this open as I think there are alternate approaches to fixing this problem besides #1444 that are worth considering.  Namely the approach that doesn't involve caching any more information in memory, but just reworking the codepaths and control flow so that we don't re-do work during the process of a single stream load
