### ISSUE TITLE
Reuse retrieved IPFS records when doing ConflictResolution

### ISSUE THREAD

**Issue by ukstv** [ceramicnetwork/js-ceramic#1444]
As exposed by [#1421](https://github.com/ceramicnetwork/js-ceramic/issues/1421), conflict resolution mechanism tries to retrieve IPFS records, even if it retrieved it before. We should avoid that.

Proposed course of action here is to split current stateless ConflictResolution class into two:
- stateful ConflictResolution: one instance per stream conflict resolution (handleTip, rewind, etc)
- stateless ConflictResolutionService: creates instances of stateful ConflictResolution.

ConflictResolution instance caches an already retrieved IPFS record after it has been read. This avoids excessive calls to IPFS.

- [ ] Rename ConflictResolution -> ConflictResolutionService
- [ ] ConflictResolutionService.applyTip should: (1) create instance of the ConflictResolution, (2) call its applyTip method.
  - Any method of the present ConflictResolutionService that is used here should be moved to ConflictResolution
  - Instead of doing naive `dispatcher.retrieve` every time, ConflictResolution should cache and reuse every retrieved IPFS record
  - The cache can be organised as a simple map: CID string -> content.
- [ ] Same with ConflictResolutionService.rewind: (1) create instance of the ConflictResolution, (2) call its rewind method.

By the end of the quest, the ConflictResolutionService is just a wrapper similar to factory pattern for instances of  ConflictResolution.

For future notice, not doing here:
As a further optimisation we might re-use already instantiated ConflictResolution instances in `Ceramic.loadStream` function. Single instance could be used for initial loading, as well as `rewind` and `atTime` operations.

See also: #1422.

**Comment by ukstv** [comment]
BTW: See https://github.com/ceramicnetwork/js-ceramic/pull/1422#issuecomment-850844535 It might be redundant to retrieve IPFS record contents.

**Comment by stbrody** [comment]
Would this mean keeping to body of every IPFS record in the log for every stream in memory?  That seems like it risks greatly increasing the memory footprint of ceramic.

**Comment by ukstv** [comment]
No, this does not persist records into memory forever. This allows to cache records already retrieved until `applyTip` is fully done.

**Comment by stbrody** [comment]
> No, this does not persist records into memory forever. This allows to cache records already retrieved until `applyTip` is fully done.

Okay cool, that sounds good then

**Comment by smrz2001** [comment]
What would you think of using a bounded LRU cache to hold streams instead of holding them only across the call to `applyTip`? That might give us the best of both worlds - the records can be reused across multiple calls to `applyTip` (among others) but will also not bust the heap.

**Comment by stbrody** [comment]
> What would you think of using a bounded LRU cache to hold streams instead of holding them only across the call to `applyTip`? That might give us the best of both worlds - the records can be reused across multiple calls to `applyTip` (among others) but will also not bust the heap.

What do you mean?  We already have an LRU cache of stream states in the Repository: https://github.com/ceramicnetwork/js-ceramic/blob/develop/packages/core/src/state-management/repository.ts#L50

But that cache doesn't contain the IPFS commit data for each individual commit in the logs

**Comment by stbrody** [comment]
Did you actually mean a bounded LRU cache of IPFS records?

That could work and would be real easy to slot into the Dispatcher

**Comment by smrz2001** [comment]
Yes, that's what I meant, sorry - bounded LRU cache of IPFS records organized by streams.

**Comment by smrz2001** [comment]
Although, it would work a little differently - once the bound is reached, _all_ the records of the oldest stream would be purged. That way, we either have the full log for a stream or have to load all of it again and never have to worry about a partial history.

**Comment by smrz2001** [comment]
I'm not quite happy with the idea of having a potentially unbounded history being loaded though, even with the current approach of storing just the CIDs - a long-lived and heavily updated stream would just destroy the system.

Should think of ways to load fewer records at a time, perhaps in batches, although each record lookup would still cost a round-trip from Ceramic <-> IPFS <-> S3, unless IPFS can support looking up batches of CIDs.

**Comment by stbrody** [comment]
> Although, it would work a little differently - once the bound is reached, _all_ the records of the oldest stream would be purged. That way, we either have the full log for a stream or have to load all of it again and never have to worry about a partial history.

Yeah that would work but does have the problem of trying to hold the full history for a large stream in memory as you mention in your next comment.  I wonder if just throwing in a real simple LRU cache of ipfs records into the dispatcher would be the best bet.  It's extremely simple and low-effort for likely high value that would cover 99% of the issues we're seeing here.

**Comment by smrz2001** [comment]
Yeah, I like that idea. Will implement it that way, thanks for brainstorming 👍🏼

**Comment by oed** [comment]
Moved this back to staging, fyi @smrz2001
