### ISSUE TITLE
Ceramic Archiver

### ISSUE THREAD

**Issue by ukstv** [ceramicnetwork/js-ceramic#1455]
**User stories:**

As a user of Ceramic I want to store Ceramic stream offline as a file.

As a user of Ceramic I want to move Ceramic streams between the networks.

As a user of Ceramic I want to upload offline-stored Ceramic stream to a network.

**Comment by oed** [comment]
> As a user of Ceramic I want to move Ceramic streams between the networks.

This wouldn't really work for any stream that has already been anchored.

**Comment by ukstv** [comment]
> > As a user of Ceramic I want to move Ceramic streams between the networks.
> 
> This wouldn't really work for any stream that has already been anchored.

True. It's a bit of a stretch here.
