### ISSUE TITLE
Set up initial CI/CD pipeline

### ISSUE THREAD

**Issue by smrz2001** [ceramicnetwork/js-ceramic#1468]

**Comment by smrz2001** [comment]
Acceptance Criterion:
Get dev branch deployed to `dev-unstable` infra immediately, without manual work needed

**Comment by v-stickykeys** [comment]
I broke this up into some sub stories to make it easier to track progress of this so scoping this down a bit

**Comment by v-stickykeys** [comment]
Also re: Joel's point from a bit ago it is probably best not to put this in js-ceramic if we can avoid it because this is all 3Box stuff

**Comment by smrz2001** [comment]
Hmm, _all_ CI/CD tools that I know of expect pipeline scripts/configuration to be part of the actual repository being tested/deployed (GitHub workflows have a folder, GitLab and AWS Code Deploy have a spec file, etc. all expected to be in the project root.)

We'll _have_ to create GitHub actions in `js-ceramic` for automated deploys on pushes and merges and if the pipeline scripts live in infra, we'll just to have to invoke them from here so I'm not entirely sure what we'd be saving.

Having said that, I can see the argument that this is 3Box infra code while the code is OSS so maybe that is the way we do it, i.e. GitHub actions that invoke scripts from infra 🤷🏻‍♂️?

@v-stickykeys @oed

**Comment by smrz2001** [comment]
As I mentioned in #1481, one option would be to look into AWS CodePipeline/CodeDeploy. They can connect externally to GitHub repos and deploy to infra based on a webhook/polling model from AWS and so we might be able to get away with not having any pipeline code in `js-ceramic`.

**Comment by oed** [comment]
Seems like webhooks could be a good model here, but don't have a strong stance!
