### ISSUE TITLE
Fix IPFS encryption errors on ELP nodes

### ISSUE THREAD

**Issue by stbrody** [ceramicnetwork/js-ceramic#1473]
It doesn't seem to be causing any noticeable issues, but it is worrisome, and we still don't understand what's different about the ELP nodes that makes it show up there but on none of our other nodes

**Comment by v-stickykeys** [comment]
I actually am thinking this probably has something to do with the DNS config. Not sure what about it.. but it feels like a config issue given that it is only happening on our elp nodes

**Comment by stbrody** [comment]
> I actually am thinking this probably has something to do with the DNS config. Not sure what about it.. but it feels like a config issue given that it is only happening on our elp nodes

at some point we had said we were going to look into the ipfs peerstore to see if there were old entries we could clear out - did we ever do that?

**Comment by ukstv** [comment]
Relevant js-ipfs issue: https://github.com/ipfs/js-ipfs/issues/3702

**Comment by creativeKoder** [comment]
has there been any updates or new information on this issue ?

**Comment by stbrody** [comment]
> has there been any updates or new information on this issue ?

Sorry no, as this doesn't seem to cause any actual problems, it hasn't been high priority for us to investigate.  We are also hoping it will go away with the upcoming switch from js-ipfs to go-ipfs

**Comment by v-stickykeys** [comment]
Looked into this a bit more today and was able to reproduce. Can confirm that this is harmless to nodes operating but it does mean a connection can not be established with a specific peer.

e.g.
```sh
val in ~ λ curl -X POST "http://localhost:5011/api/v0/swarm/connect?arg=/dns4/ceramic-node.vitalpointai.com/tcp/4012/ws/p2p/QmVH335h3srKvSTZKr5bcLFbnvfVZSewVzpkbEX9XHcLsQ" | jq
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  1593  100  1593    0     0   5966      0 --:--:-- --:--:-- --:--:--  5966
{
  "Message": "\n    Error: Error occurred during XX handshake: Error occurred while verifying signed payload: Peer ID doesn't match libp2p public key.\n        at Noise.performXXHandshake (/Users/val/.nvm/versions/node/v14.15.1/lib/node_modules/@ceramicnetwork/ipfs-daemon/node_modules/libp2p-noise/dist/src/noise.js:186:19)\n        at runMicrotasks (<anonymous>)\n        at async Noise.performHandshake (/Users/val/.nvm/versions/node/v14.15.1/lib/node_modules/@ceramicnetwork/ipfs-daemon/node_modules/libp2p-noise/dist/src/noise.js:155:20)\n        at async Noise.secureOutbound (/Users/val/.nvm/versions/node/v14.15.1/lib/node_modules/@ceramicnetwork/ipfs-daemon/node_modules/libp2p-noise/dist/src/noise.js:80:27)\n        at async Upgrader._encryptOutbound (/Users/val/.nvm/versions/node/v14.15.1/lib/node_modules/@ceramicnetwork/ipfs-daemon/node_modules/libp2p/src/upgrader.js:406:12)\n        at async Upgrader.upgradeOutbound (/Users/val/.nvm/versions/node/v14.15.1/lib/node_modules/@ceramicnetwork/ipfs-daemon/node_modules/libp2p/src/upgrader.js:176:11)\n        at async ClassIsWrapper.dial (/Users/val/.nvm/versions/node/v14.15.1/lib/node_modules/@ceramicnetwork/ipfs-daemon/node_modules/libp2p-websockets/src/index.js:54:18)\n        at async TransportManager.dial (/Users/val/.nvm/versions/node/v14.15.1/lib/node_modules/@ceramicnetwork/ipfs-daemon/node_modules/libp2p/src/transport-manager.js:111:14)\n        at async /Users/val/.nvm/versions/node/v14.15.1/lib/node_modules/@ceramicnetwork/ipfs-daemon/node_modules/libp2p/src/dialer/dial-request.js:71:18",
  "Code": 0,
  "Type": "error"
}
```

However, this **_does not_** cause IPFS and/or Ceramic to crash and can be safely ignored for the time being.

**Comment by v-stickykeys** [comment]
> We are also hoping it will go away with the upcoming switch from js-ipfs to go-ipfs

Same issue with go @stbrody 
```json
{
  "Message": "connect QmVH335h3srKvSTZKr5bcLFbnvfVZSewVzpkbEX9XHcLsQ failure: failed to dial QmVH335h3srKvSTZKr5bcLFbnvfVZSewVzpkbEX9XHcLsQ: all dials failed\n  * [/ip4/40.86.207.149/tcp/4012/ws] failed to negotiate security protocol: peer id mismatch: expected QmVH335h3srKvSTZKr5bcLFbnvfVZSewVzpkbEX9XHcLsQ, but remote key matches QmVa6vVRnG9qTte2sV13W4XXTNsSPegPS8Wr31Qo294g6o",
  "Code": 0,
  "Type": "error"
}
```

**Comment by oed** [comment]
Does this happen for any of the peers in the peerlist? If so they might have the wrong peerId?
