### ISSUE TITLE
Queue ceramic deploys on push

### ISSUE THREAD

**Issue by smrz2001** [ceramicnetwork/js-ceramic#1481]
- Must not deploy while integration tests are running
- Use AWS CodePipeline to queue deploys to the same env
- Add DynamoDB lock while tests are running (whether manual, periodic, or through pipeline) and wait for them to complete before deploying

**Comment by v-stickykeys** [comment]
@smrz2001 Is dynamodb necessary? My first thought for this was just check the running tasks on ECS and estimate completion time, then periodically check before deploy with some final timeout at which point the deploy will fail

**Comment by v-stickykeys** [comment]
This should not be in js-ceramic and instead we should put everything in our infra repo if possible because this is code for 3Box

**Comment by smrz2001** [comment]
> This should not be in js-ceramic and instead we should put everything in our infra repo if possible because this is code for 3Box

Will might have to be in both, IMO. See my reply here:
https://github.com/ceramicnetwork/js-ceramic/issues/1468#issuecomment-870927629

I don't think we can avoid adding pipeline code to `js-ceramic` because of the way GitHub actions work but we can possibly move the bulk of any scripts to infra.

**Comment by smrz2001** [comment]
I guess one option would be to look into AWS CodePipeline/CodeDeploy. They can connect to GitHub repos and deploy to infra and we might be able to set up a pipeline that is based on a webhook/polling model from AWS versus using GitHub actions.

**Comment by smrz2001** [comment]
> @smrz2001 Is dynamodb necessary? My first thought for this was just check the running tasks on ECS and estimate completion time, then periodically check before deploy with some final timeout at which point the deploy will fail

We could - what you're suggesting is a polling model. My concern there would be race conditions as the team grows and we have multiple merges happening close together. Multiple jobs in the queue might get processed and estimate similar times of completion, and then trample each other's test runs. An explicit lock (whether in DynamoDB, or elsewhere) _ensures_ that serialization is maintained between operations.

**Comment by smrz2001** [comment]
This is now actually a `ceramic-infra` ticket but I can't move it there. Instead of closing this and creating another one, I'm just going to pretend this is a infra ticket. Does that work or should I close this and open an infra ticket?
