### ISSUE TITLE
3id-did-resolver reports un-anchored version

### ISSUE THREAD

**Issue by ukstv** [ceramicnetwork/js-ceramic#1520]
Scenario:
1. A person creates a 3id `did:3:foo` (`foo` here is a placeholder for the actual identifier).
2. 3id-did-resolver is called to resolve `did:3:foo`: it reports `versionId: "0"`.
3. A person initiates key rotation.
4. 3id-did-resolver is called to resolve `did:3:foo` (no version), before the respective tile gets anchored: it reports `versionId: "update-commit"`, where `update-commit` is a CID of the update commit.

I assumed, that 3id DID is versioned by anchor commits. If the assumption is true, on step 4 the resolver should respond with version 0, rather than un-anchored version. And only after the respective tile gets anchored, `did:3:foo` should resolve to a new version.

If it is indeed a bug, the fix is to resolve only the last _anchored_ version.

CC @oed

**Comment by oed** [comment]
Interesting nuance. Don't have a strong opinion what the correct behavior should be. Most of the time we assume that the DID provider adds a `versionId` in the `kid`, so I don't think we would run into any issues in Ceramic. However the 3ID DID Provider doesn't use the new keys to sign until the update has been anchored, so it could still make sense to just resolve the latest anchored version as you are suggesting.

**Comment by ukstv** [comment]
It is stated in the spec, it makes sense, so I definitely consider this a bug.

[Spec](https://github.com/ceramicnetwork/CIP/blob/main/CIPs/CIP-79/CIP-79.md#did-document-metadata): "versionId - should be equal to the commit CID from the most recent AnchorCommit"
