### ISSUE TITLE
Check the signature timestamp for genesis if either have a tip, or it is a lone genesis via whole-log application

### ISSUE THREAD

**Issue by ukstv** [ceramicnetwork/js-ceramic#1530]
There can be a case, when a stream has only genesis commit. Its signature has to be verified. On the other hand, a stream can has more commits, which can provide timestamp information important for signature verification. A Ceramic node has to verify only lone-genesis signature, while postponing verification for multi-commit streams until all the commits are available.

This could be achieved via whole-log commit application, instead of doing two part "create stream from genesis" then "apply tip".

**Comment by ukstv** [comment]
CC @stbrody

**Comment by stbrody** [comment]
Wasn't this already done in https://github.com/ceramicnetwork/js-ceramic/pull/1529?

**Comment by ukstv** [comment]
@stbrody I'd say it was "fixed". The current implementation is fragile and under-performant. Changed the name here stressing the whole-log part.
