### ISSUE TITLE
multiQuery() should report errors from the individual queries

### ISSUE THREAD

**Issue by stbrody** [ceramicnetwork/js-ceramic#1553]
The multiQuery() function swallows all error from each individual query it is given, losing any information about what went wrong.  Instead it should still return the error information in some way to the client.

**Comment by oed** [comment]
I guess this should be part of the Error handling initiative?

**Comment by oed** [comment]
I guess this should be part of the Error handling initiative?

**Comment by stbrody** [comment]
> I guess this should be part of the Error handling initiative?

hmm... it's not strictly related, but it may become easier to do this after doing that as we'll have a standard format for how to serialize the errors over the wire.  I can add a note to the initiative
