### ISSUE TITLE
The URL including the instructions to install the CLI does not resolve giving a 404 error

### ISSUE THREAD

**Issue by dentropy** [ceramicnetwork/js-ceramic#1618]
The URL including the instructions to install the CLI does not resolve giving a 404 error

"Ceramic CLI" link on page -> https://developers.ceramic.network/build/cli/quick-start/#1-install-the-cli

https://developers.ceramic.network/build/cli/quick-start/cli/installation.md

**Comment by Sterahi** [comment]
Hey dentropy, 

Thanks for reporting this. I'll be fixing that very quickly, but for now you can go to: https://developers.ceramic.network/build/cli/installation/ and you'll be able to see the proper instructions.
