### ISSUE TITLE
Bug: Our peer is not in the list of connected peers printed by the console

### ISSUE THREAD

**Issue by lyd0** [ceramicnetwork/js-ceramic#1697]
**Describe the bug**

when we run the ceramic daemon with elp in two servers.  The console showed that we connect to other peers using mainnet.json file (which have our node when we open this file in the browser).  But the console do not show our peer and some other peers, e.g., ceramic-node.vitalpointai.com.

And other daemon we ran, showed that we connected to all other peers except our ipfs.xx.ownershiplabs.com

**To Reproduce**
1. Start ceramic process（ceramic daemon --network elp --ipfs-api myIpfsHostUrl）

**Expected behavior**
The console should print our peer address( "/dns4/ipfs-ceramic-elp-external.ownershiplabs.com/tcp/4012/ws/p2p/QmSiSc4WetTWsNzv8ukpXk57tyDNVqwbvMAKp1MUvo5pF8") if our peer is in the mainnet.json(https://raw.githubusercontent.com/ceramicnetwork/peerlist/main/mainnet.json)

**Ceramic versions** 
1.3.0

**Machine, OS, browser information (please complete the following information):**
ubuntu

**Additional context**
Here is what the console prints without our peer address( "/dns4/ipfs-ceramic-elp-external.ownershiplabs.com/tcp/4012/ws/p2p/QmSiSc4WetTWsNzv8ukpXk57tyDNVqwbvMAKp1MUvo5pF8")

Connecting to ceramic network 'elp' using pubsub topic '/ceramic/mainnet'
Connecting to peers found in 'https://raw.githubusercontent.com/ceramicnetwork/peerlist/main/mainnet.json'
Connected to peers: /dns4/ceramic-node.vitalpointai.com/tcp/4012/ws/p2p/QmVH335h3srKvSTZKr5bcLFbnvfVZSewVzpkbEX9XHcLsQ, /dns4/ipfs-ceramic-public-mainnet-external.ceramic.network/tcp/4012/wss/p2p/QmS2hvoNEfQTwqJC4v6xTvK8FpNR2s6AgDVsTL3unK11Ng, /dns4/ipfs-ceramic-private-mainnet-external.3boxlabs.com/tcp/4012/wss/p2p/QmXALVsXZwPWTUbsT8G6VVzzgTJaAWRUD7FWL5f7d5ubAL, /dns4/ipfs-ceramic-elp-1-1-external.3boxlabs.com/tcp/4012/wss/p2p/QmUiF8Au7wjhAF9BYYMNQRW5KhY7o8fq4RUozzkWvHXQrZ, /dns4/ipfs-cas-mainnet-external.3boxlabs.com/tcp/4012/wss/p2p/QmUvEKXuorR7YksrVgA7yKGbfjWHuCRisw2cH9iqRVM9P8, /dns4/ipfs-ceramic-elp-1-2-external.3boxlabs.com/tcp/4012/wss/p2p/QmRNw9ZimjSwujzS3euqSYxDW9EHDU5LB3NbLQ5vJ13hwJ, /ip4/3.20.66.20/tcp/40281, /dns4/ipfs-cas-clay-external.3boxlabs.com/tcp/4012/wss/p2p/QmbeBTzSccH8xYottaYeyVX8QsKyox1ExfRx7T1iBqRyCd, /ip4/165.232.129.204/tcp/4012/ws/p2p/QmbDGaByZoomn3NQQjZzwaPWH6ei3ptzWK7a7ECtS35DKL, /dns4/ipfs-ceramic-public-clay-external.3boxlabs.com/tcp/4012/wss/p2p/QmWiY3CbNawZjWnHXx3p3DXsg21pZYTj4CRY1iwMkhP8r3, /dns4/ipfs-ceramic-public-clay-external.ceramic.network/tcp/4012/wss/p2p/QmSqeKpCYW89XrHHxtEQEWXmznp6o336jzwvdodbrGeLTk
Connected to anchor service 'https://cas.3boxlabs.com' with supported anchor chains ['eip155:1']

**Comment by stbrody** [comment]
Note that [a node will not attempt to connect to itself](https://github.com/ceramicnetwork/js-ceramic/blob/caf01637d5ceadabcef0e2b0bb5b52da2a3eeef0/packages/ipfs-topology/src/ipfs-topology.ts#L138-L142).  So long as your node is able to load streams from the network, and other nodes on the network are able to load streams from your node, then you should be fine.  Easiest way to test the latter is to try to load a stream created on your node via the gateway: https://gateway.ceramic.network
