### ISSUE TITLE
Cannot change 'deterministic' or 'unique' properties on existing Streams

### ISSUE THREAD

**Issue by gertig** [ceramicnetwork/js-ceramic#1714]
**Describe the bug**
Calling `idx.set("basicProfile", { name: "testing" })` fails with error `Cannot change 'deterministic' or 'unique' properties on existing Streams`

**Expected behavior**
Creation of a new BasicProfile for the authenticated DID.

**Ceramic versions** 
`Ceramic Daemon at version 1.3.1`

**Machine, OS, browser information (please complete the following information):**
Mac 11.5.2

**Additional context**
https://github.com/ceramicnetwork/js-ceramic/pull/1688/files#r706555308

**Comment by oed** [comment]
@gertig try updating to the latest version of IDX this is a bug that should have been fixed!

**Comment by gertig** [comment]
That fixed it!

**Comment by oed** [comment]
Glad to hear it :)
