### ISSUE TITLE
`multiQuery` call on deterministic stream doesn't return the stream when there are no updates

### ISSUE THREAD

**Issue by PaulLeCam** [ceramicnetwork/js-ceramic#1797]
**Describe the bug**

When creating deterministic streams, the client expectation is that the node will always return a stream, whether it's the empty genesis state or the latest state after further updates.
When using `multiQuery()` with a deterministic stream (providing `streamId` and `genesis`) however, the node only returns the expected stream if there has been updates.

**To Reproduce**

```ts
// 1. Create the genesis commit and stream ID
const genesis = await TileDocument.makeGenesis({}, null, {
  controllers: ['did:key:...'],
  family: 'IDX',
  deterministic: true,
}))
const streamId = await StreamID.fromGenesis('tile', genesis)
// 2. Run the multiquery
const streams = await ceramic.multiQuery([{ streamId, genesis }])
// 3. streams is an empty object
```

**Expected behavior**

The returned object from the server should contain the stream with its genesis state.

**Screenshots**

**Ceramic versions** 
Daemon v1.6.1

**Machine, OS, browser information (please complete the following information):**
macOS 10.14.6

**Comment by stbrody** [comment]
FYI @haardikk21

**Comment by stbrody** [comment]
Actually, @PaulLeCam, we have a unit test already that is basically exactly what you put as the steps to repro: https://github.com/ceramicnetwork/js-ceramic/blob/develop/packages/core/src/__tests__/ceramic.test.ts#L489-L525

I don't see anything different between that test and what you're doing that would explain the difference in behavior you're seeing.  Are you sure you're testing against a recent version of Ceramic that includes the support for the genesis field in multiqueries?

**Comment by stbrody** [comment]
Simpler repro: https://github.com/ceramicnetwork/issue-1797-setup/blob/main/run.mjs

**Comment by stbrody** [comment]
I think I figured out the issue.  https://github.com/ceramicnetwork/js-ceramic/commit/3e084638467d2d8983835d3836aec3049ae82920 didn't make any chances to the http client to expose the new `genesis` property.  The multiquery method in the http client only passes on the fields it expects to see: https://github.com/ceramicnetwork/js-ceramic/blob/072f95483801c91b72b127aee307236df842407f/packages/http-client/src/ceramic-http-client.ts#L146-L152

**Comment by stbrody** [comment]
probably that `map` call should convert the streamid to a string, but otherwise pass through all other given query properties as is, so that extra properties can be given even if the http client doesn't explicitly expect them
