### ISSUE TITLE
Reject anchors not from our CAS

### ISSUE THREAD

**Issue by stbrody** [ceramicnetwork/js-ceramic#1798]
Our mainnet CAS has a well-known ethereum address.  We should only allow anchor commits created from that ethereum address, and reject any anchor commits from other addresses.  This is a stopgap until we move anchoring to happen via a smart contract, which will include an allowlist of trusted anchor services.

**Comment by stbrody** [comment]
Probably makes sense to do this for mainnet and Clay, but leave dev-unstable able to accept anchors from any address.

CC @v-stickykeys @oed

**Comment by oed** [comment]
`whitelist` -> `allowlist` :)

**Comment by v-stickykeys** [comment]
> Probably makes sense to do this for mainnet and Clay, but leave dev-unstable able to accept anchors from any address.
> 
> CC @v-stickykeys @oed

Better to do it on dev as well to test behavior

**Comment by stbrody** [comment]
@v-stickykeys - can you provide the ethereum wallet address for the CAS on each of our networks?
