### ISSUE TITLE
Pin newly created streams by default

### ISSUE THREAD

**Issue by stbrody** [ceramicnetwork/js-ceramic#1805]
https://github.com/ceramicnetwork/js-ceramic/issues/677 added an option to stream creation requests to pin the newly created stream, but left the default behavior as-is.  We should make the `pin` flag default to true for create requests so that newly created streams are pinned by default.

**Comment by stbrody** [comment]
Related to, but distinct from, https://github.com/ceramicnetwork/js-ceramic/issues/676

**Comment by oed** [comment]
Make sure it doesn't error on deterministic streams when running in gateway mode.

**Comment by stbrody** [comment]
Moved to linear
