### ISSUE TITLE
Convert Cacao object to Cacao block representation - IPLD and DAG-CBOR

### ISSUE THREAD

**Issue by haardikk21** [ceramicnetwork/js-ceramic#1835]

**Comment by haardikk21** [comment]
Look into converting JSON payload into DAG CBOR bytes representation, and place the deterministic CID into CacaoBlock

**Comment by haardikk21** [comment]
Tests to match snapshots

**Comment by oed** [comment]
Use ***@***.***/dag-cbor` :)

Sent via Superhuman iOS ***@***.***>
