### ISSUE TITLE
Caip10Link: Accept optional `asDid` parameter to represent signed commits through a capability

### ISSUE THREAD

**Issue by haardikk21** [ceramicnetwork/js-ceramic#1837]

**Comment by ukstv** [comment]
Hey, apparently, this is not needed. At all. My mistake. Closing.

**Comment by oed** [comment]
Wait why?


Sent via Superhuman ***@***.***>

**Comment by ukstv** [comment]
Caip10Link genesis contains just a declaration of a DID that supposedly owns a blockchain account, no signatures in any form here. Caip10Link signed commit contains a signature made by the blockchain account. No place for capability in the scheme.

**Comment by oed** [comment]
Oh, This is Caip10Link! Nvm :)

Sent via Superhuman ***@***.***>
