### ISSUE TITLE
Transition to ESModules and ES2020

### ISSUE THREAD

**Issue by ukstv** [ceramicnetwork/js-ceramic#1850]
- [ ] 3id-did-resolver
- [ ] common
- [ ] key-did-resolver
- [ ] pkh-did-resolver
- [ ] blockchain-utils-linking
- [ ] core
- [ ] logger
- [ ] stream-caip10-link
- [ ] blockchain-utils-validation
- [ ] http-client
- [ ] pinning-aggregation
- [ ] stream-caip10-link-handler
- [ ] canary-integration
- [ ] ipfs-daemon
- [ ] pinning-ipfs-backend
- [ ] stream-tile
- [ ] cli
- [ ] ipfs-topology
- [ ] pinning-powergate-backend
- [ ] stream-tile-handler

**Comment by glcohen** [comment]
Consider splitting

**Comment by ukstv** [comment]
@glcohen It is quite hard to split, since the packages share most of the ancillary infrastructure.
