### ISSUE TITLE
node-fetch alternative

### ISSUE THREAD

**Issue by simonovic86** [ceramicnetwork/js-ceramic#186]
Good point in the [PR](https://github.com/ceramicnetwork/js-ceramic/pull/185#issue-456819152).

```
node-fetch unfortunately doesn't support isomorphic browser & node fetching,
cross-fetch falls back to a whatwg brower fetch when it detects a windows object (think it's also officially used by js-ipfs)
```

Replace `node-fetch` with `cross-fetch`.

**Comment by oed** [comment]
Just for reference: The reason I initially chose to use `node-fetch` was because of its tiny package size: https://bundlephobia.com/result?p=node-fetch@2.6.0

Compared to `cross-fetch`: https://bundlephobia.com/result?p=cross-fetch@3.0.5
