### ISSUE TITLE
Add client side timeout to http client requests

### ISSUE THREAD

**Issue by stbrody** [ceramicnetwork/js-ceramic#1875]
https://github.com/ceramicnetwork/js-ceramic/blob/07cbc9108415c8e71c268e10acf9238f65460a1e/packages/common/src/utils/http-utils.ts#L9

**Comment by ukstv** [comment]
Copied from Discord by @PaulLeCam :
> If you're planning on adding timeouts in the client, maybe adding an option to provide an abort signal could be added as well as part of the change? That would allow the consumer to cancel requests as needed, for example to manage their own (shorter) timeout or even user-initiated cancellations?
