### ISSUE TITLE
ipfs pin - does it try to retrieve aka decode block?

### ISSUE THREAD

**Issue by ukstv** [ceramicnetwork/js-ceramic#1886]

**Comment by ukstv** [comment]
Both go-ipfs and js-ipfs can not pin an invalid block. Internally, they try to parse it with a strict codec.

**Comment by ukstv** [comment]
We could reasonably expect this problem to disappear, after dag-cbor restrictions are lifted.

**Comment by oed** [comment]
Reopening and putting in staging.
