### ISSUE TITLE
Sanitize possible undefined's in js-ceramic where dag-cbor codec is used

### ISSUE THREAD

**Issue by ukstv** [ceramicnetwork/js-ceramic#1888]

**Comment by oed** [comment]
Maybe we leave this to the application?

**Comment by ukstv** [comment]
IMO, considering Joel's comment above ^ and continuation of discussion on https://github.com/ceramicnetwork/ceramic/issues/205 it makes sense to close this one.

**Comment by stbrody** [comment]
yeah I think it makes sense that if a user tries to create a stream with an undefined value in the content that they get an error.  The one thing I would consider doing in js-ceramic here is possibly throwing the error ourselves, or wrapping the error message thrown from IPLD, depending on how clear the error message that ipfs throws is.
