### ISSUE TITLE
Use `block.get` in retrieveCommit

### ISSUE THREAD

**Issue by oed** [ceramicnetwork/js-ceramic#1889]
Change the [`_getFromIpfs`](https://github.com/ceramicnetwork/js-ceramic/blob/develop/packages/core/src/dispatcher.ts#L153) method in the following way:

* If `path` is **not** set, use `block.get` instead of `dag.get` [here](https://github.com/ceramicnetwork/js-ceramic/blob/develop/packages/core/src/dispatcher.ts#L169).
* Otherwise no change

**Comment by glcohen** [comment]
workaround not relevant
