### ISSUE TITLE
ceramic.setDIDProvider does not seem to respect async getConsent function calls with IdentityWallet DID provider

### ISSUE THREAD

**Issue by Schwartz10** [ceramicnetwork/js-ceramic#191]
I'm not sure if I'm just misusing something, but i'm running into something unexpected:

```js
const ipfs = IpfsHttpClient({ url: IPFS_URL });
const ceramic = await Ceramic.create(ipfs, {
   stateStorePath: "./ceramic.lvl",
});

const getConsent = () => {
   return new Promise(resolve => {
       setTimeout(() => {
            console.log("LOG A")
            return resolve(true)
       }, 1000)
   })
}

const idWallet = new IdentityWallet(getConsent, { seed: randomBytes })

await ceramic.setDIDProvider(idWallet.get3idProvider());
console.log("LOG B")
```

In this example, I'd expect to see the logs go in the following order:

LOG A
LOG B

But I'm seeing the opposite - `setDIDProvider` finishes before `getConsent` returns anything. Is this a bug? Am i misusing something?

**Comment by simonovic86** [comment]
Thanks for the feedback @Schwartz10 ! We'll look at it asap.

**Comment by Schwartz10** [comment]
Thanks for the quick response! A separate but related piece of feedback (which is less important), I'd expect that if `getConsent` returns false, `await ceramic.setDIDProvider` should somehow be able to relay this information back to the caller - either by `throw`ing some "no consent given" error, or returning some type of falsey value.

**Comment by simonovic86** [comment]
@Schwartz10 makes sense!

**Comment by simonovic86** [comment]
@Schwartz10 I modified the `ceramic-daemon` in order to reproduce the issue and I'm seeing the correct log (A,B). The modification is:

```javascript
    const getConsent = (): Promise<boolean> => {
      return new Promise(resolve => {
        setTimeout(() => {
          console.log("LOG A")
          return resolve(true)
        }, 5000)
      })
    }

    const idWallet = new IdentityWallet(getConsent, { seed: cliConfig.seed })
    await ceramic.setDIDProvider(idWallet.get3idProvider())

    console.log("LOG B")

    return new CeramicDaemon(ceramic, opts)
```

**Comment by Schwartz10** [comment]
@simonovic86 interesting! I pulled the latest and linked it to my local setup, problem seems to be fixed! Sorry about that, i'll stick to working off the local develop branch for now

**Comment by simonovic86** [comment]
@Schwartz10 awesome! no worries, feel free to ping anytime! :)
