### ISSUE TITLE
Do not return from create/update request until after anchor request has been successfully made on the CAS

### ISSUE THREAD

**Issue by stbrody** [ceramicnetwork/js-ceramic#1919]
Currently if you create or update a stream and request an anchor, the actual work of requesting the anchor is done asynchronously in the background, so the create/update request returns before the anchor request is even made.  This has several implications - for one thing, it makes testing much harder as many of the tests now have non-deterministic timing related to whether the anchor request is present on the CAS by the time the Ceramic operation has returned.  More importantly to regular users, it means that if there's any problem creating the anchor request (say the CAS is down, or the wrong CAS url is configured for the ceramic node), the application won't get an error.  The ceramic stream create/update request will succeed, but no anchor will ever happen.  The only way to know anything is wrong is to check the ceramic node logs.

While we can't wait inline for the anchor to *complete* we can at least wait inline to make sure the anchor request is *created* successfully.

**Comment by ukstv** [comment]
> More importantly to regular users, it means that if there's any problem creating the anchor request (say the CAS is down, or the wrong CAS url is configured for the ceramic node), the application won't get an error. The ceramic stream create/update request will succeed, but no anchor will ever happen. The only way to know anything is wrong is to check the ceramic node logs.

We discussed this during refactor time, if I am not mistaken. I dare to reiterate the points we made then, so the decision to move forward with this proposal is fully informed. (1) It is not a user's responsibility to figure if anything is wrong with a node configuration. It is on the node operator. (2) This would increase response time for such a request. From a user's standpoint, this leads to a degraded UX.
