### ISSUE TITLE
log base streamid + commit CID instead of CommitID for multiquery errors

### ISSUE THREAD

**Issue by stbrody** [ceramicnetwork/js-ceramic#1931]

**Comment by oed** [comment]
It would be nice if we had a cli tool to decompose a commitID into streamId and commit CID. Might be good to add to glaze?
e.g.
```sh
glaze commit-info <commit-id>
```
cc @Sterahi @PaulLeCam

**Comment by stbrody** [comment]
> It would be nice if we had a cli tool to decompose a commitID into streamId and commit CID. Might be good to add to glaze? e.g.
> 
> ```shell
> glaze commit-info <commit-id>
> ```

+1 that would be very useful!  Would also be nice to be able to go the other direction - provide streamid and commit CID, get CommitID back
