### ISSUE TITLE
Migrate did-jwt to noble-crypto

### ISSUE THREAD

**Issue by ukstv** [ceramicnetwork/js-ceramic#1960]
As it uses ES2020 anyway, we should make a PR that changes (old and slow) crypto libraries with noble-crypto.

**Comment by oed** [comment]
This is already tracked upstream: https://github.com/decentralized-identity/did-jwt/issues/208

**Comment by ukstv** [comment]
Can we still have it here as a reminder, please? I would really like to measure speed up in Ceramic after the upgrade, for example.
