### ISSUE TITLE
Wait for pubsub unsubscribe to complete before returning from Dispatcher.stop()

### ISSUE THREAD

**Issue by stbrody** [ceramicnetwork/js-ceramic#1963]
When shutting down the dispatcher, we [unsubscribe from the message bus](https://github.com/ceramicnetwork/js-ceramic/blob/1a49609123c014b7c1a35136a0cb3f6c0abfc965/packages/core/src/dispatcher.ts#L307), which unsubscribes from the `Pubsub` object, which unsubscribes from `IncomingChannel`, which is what is actually responsible for unsubscribing from the underlying ipfs pubsub topic.  The problem is that unsubscribing from IncomingChannel only [enqueues a task to unsubscribe from ipfs](https://github.com/ceramicnetwork/js-ceramic/blob/1a49609123c014b7c1a35136a0cb3f6c0abfc965/packages/core/src/pubsub/incoming-channel.ts#L64), without actually waiting for the unsubscribe to complete.  This means that at the time that the `Dispatcher.close()` promise resolves, we can still have an outstanding connection to the ipfs node long-polling for pubsub messages.  This can cause problems in tests that expect all open handles to be gone by the time [Ceramic.close()](https://github.com/ceramicnetwork/js-ceramic/blob/1a49609123c014b7c1a35136a0cb3f6c0abfc965/packages/core/src/ceramic.ts#L763) completes.

**Comment by stbrody** [comment]
FYI @ukstv

**Comment by stbrody** [comment]
@ukstv any idea how hard this would be to fix?  I assume it was done this way because you can't `await` async work in the unsubscribe handler for an rxjs Observable?

**Comment by ukstv** [comment]
`unsubscribe` indeed is a bit naive.

The way to go is to maintain a task queue somewhere - on MessageBus, or on Dispatcher, and then when doing `Dispatcher.close` - wait till it is idle.
