### ISSUE TITLE
Bug: Cannot determine StreamID of anchored streams from an anchor batch merkle tree.

### ISSUE THREAD

**Issue by stbrody** [ceramicnetwork/js-ceramic#1967]
Indexing systems for Ceramic should be able to watch ethereum for anchors to our CAS' well known address, get the root of the anchor merkle tree from the transaction call data, then walk the merkle tree to find the commits that were anchored, and from that maintain an index of the streams that were updated.  Currently, however, while you can get the commits that were anchored, finding what StreamIDs those correspond to is not obvious.

The anchor merkle tree leaf nodes are the CIDs of the SignedCommits that are anchored in that batch.  The SignedCommits themselves have an `id` field which is the CID of the genesis commit, but there is no `type` field specifying the streamtype of the associated stream.  Without the streamtype one cannot turn the genesis CID into the Stream's StreamID.  For now since there are only 2 streamtypes this can be crudely worked around by checking if the `family` in the genesis commit metadata begins with "caip10-" (and assuming it's a caip10 link if so and a tile document if not).  But really the `type` of the stream should be encoded somewhere more explicitly so one can easily compute the StreamID directly.

The obvious place to put this would be in the header for the GenesisCommit of all streams, but unfortunately this would break deterministic lookup of existing streams.  Other potential options of how to do this are:
* Encode the `type` into every commit *except* the genesis commit.  This would still make it hard to determine the StreamID from an anchor merkle tree that is anchoring a genesis commit.  This could be done by changing the `id` field in commits to be the StreamID instead of the genesis CID.  Ticket for making that change is tracked here: https://github.com/ceramicnetwork/js-ceramic/issues/1968
* Encode the type into the leaf nodes of the anchor merkle tree.  This is likely the best/most complete solution.  Work to do this is tracked here: https://github.com/ceramicnetwork/ceramic-anchor-service/issues/565

**Comment by oed** [comment]
The most obvious fix to me would be to put the streamId in the `id` property instead of the genesis CID. Essentially just adding information about type to each commit.

**Comment by oed** [comment]
> Encode the type into every commit except the genesis commit. This would still make it hard to determine the StreamID from an anchor merkle tree that is anchoring a genesis commit

This is a fair point. I guess it wouldn't be too difficult to introduce a function that determines streamtype based on the content of the genesis commit.
