### ISSUE TITLE
Create Ceramic 1.0 branch, merge 2.0 branch into develop

### ISSUE THREAD

**Issue by stbrody** [ceramicnetwork/js-ceramic#1972]
I couldn't find an existing epic that made sense for this, so I made a new epic: https://github.com/ceramicnetwork/js-ceramic/issues/1971.

I figure we can use that new epic for any final miscellaneous work to get the go-ipfs release tied up in a bow and fully out the door.  FYI @ukstv @oed @decentralgabe

**Comment by oed** [comment]
Can we name the branch `v1.x.x`?
