### ISSUE TITLE
Make typedoc work again

### ISSUE THREAD

**Issue by ukstv** [ceramicnetwork/js-ceramic#1978]
1. Apparently, we do not include `typedoc-plugin-lerna-packages` as a dev dependency. It is required for our typedoc setting.
2. Typedoc plugin `typedoc-plugin-pages` tries to import `./dist/lib/utils/options/declaration` which is not exported by Typedoc. It seems, that in Node.js v16 resolution algorithm has changed. It now prohibits using deep internal files of one package in another. I (S.U.) do not have a good idea on how to fix it other than to make a PR to Typedoc that makes it compatible with newer Node.js and ESM.

CC @stephhuynh18 @oed

**Comment by oed** [comment]
1. Looks like it was removed in https://github.com/ceramicnetwork/js-ceramic/pull/1961 why? ([It's present in 2.x branch](https://github.com/ceramicnetwork/js-ceramic/blob/release/2.x-progress/package.json#L40))
2. Let's disable the pages plugin for now. It doesn't add too much value. Let's keep the content around for when js-ceramic gets its own docsite.

**Comment by ukstv** [comment]
> * Looks like it was removed in [Feat/expose pure esm and ipfs upgrade #1961](https://github.com/ceramicnetwork/js-ceramic/pull/1961) why? ([It's present in 2.x branch](https://github.com/ceramicnetwork/js-ceramic/blob/release/2.x-progress/package.json#L40))

After transition to ESM it broke. That's the reason for disabling it and creating this issue. It can not run atm.

**Comment by oed** [comment]
Ok, generating the documentation doesn't really work without it. I would say that this is a blocker for the full 2.0 release.
