### ISSUE TITLE
URGENT: Remove @overnightjs/logger or enforce package-lock.json

### ISSUE THREAD

**Issue by vaultec81** [ceramicnetwork/js-ceramic#1980]
**Describe the bug**
Recently, the maintainer of the `colors` npm package has decided to go rogue. Read me [here](https://github.com/Marak/colors.js/commit/074a0f8ed0c31c35d13d28632bd8a049ff136fb6) and [here](https://www.reddit.com/r/javascript/comments/rz56qu/marak_adds_infinite_loop_to_colorsjs/)
The package `@overnightjs/logger` used in Ceramic depends on `colors`

**To Reproduce**

The nodejs code below will demonstrate this issue.  <h3>**NOTE: you will need to do a fresh install with no package-lock.json or already existing node_modules.**.</h6>
```

import CeramicHTTP from '@ceramicnetwork/http-client'

const ceramic = new CeramicHTTP('<ceramic API url>')

```

**Screenshots**
After running the above code

![image](https://user-images.githubusercontent.com/47548474/148665415-179331cd-8377-42c1-9c16-ca74e8fe56a6.png)

And thousands of lines of garbage data being put out.

**Ceramic versions** 
As far as I am aware this affects all ceramic versions. Any version that uses `@overnightjs/logger` or `colors` npm package directly or indirectly.

I was running Ceramic http client v 1.4.0 but it also happens on latest.

A quick work around is having a package-lock.json, however, new installs will not have this available.

**Comment by v-stickykeys** [comment]
Have been able to reproduce the issue as well.

**Comment by v-stickykeys** [comment]
Create a PR and you can use this branch to run js-ceramic without the issue until we create a new release.

**Comment by oed** [comment]
Thank you for reporting this @vaultec81! I believe the issue should now be addressed. Can you confirm?

**Comment by oed** [comment]
Separate note: Seems like `@overnight/logger` has been deprecated: https://github.com/seanpmaxwell/overnight#overnightjs

We should make sure to replace this with something different. @ukstv @stephhuynh18 @stbrody

**Comment by vaultec81** [comment]
> Thank you for reporting this @vaultec81! I believe the issue should now be addressed. Can you confirm?

Yep! Fixed on my end!

**Comment by ukstv** [comment]
> Separate note: Seems like `@overnight/logger` has been deprecated: https://github.com/seanpmaxwell/overnight#overnightjs
> 
> We should make sure to replace this with something different. @ukstv @stephhuynh18 @stbrody

It has already been replaced with jet-logger by @stephhuynh18 in 2.x

**Comment by oed** [comment]
Nice :)
