### ISSUE TITLE
[Exception in ceramic.did.authenticate]

### ISSUE THREAD

**Issue by client03** [ceramicnetwork/js-ceramic#1984]
**Describe the bug**
https://gist.github.com/dabit3/ba326e47e4882073bd6342dc1998fd16

Run following code inside docker with `node:current-alpine` image.
Connection with metamask extension and signature completes successfully.
On `await ceramic.did.authenticate()` calling happens an exception:

```
did.ts:260 Uncaught (in promise) TypeError: did_jwt_1.verifyJWS is not a function
    at DID.<anonymous> (did.ts:260:1)
    at Generator.next (<anonymous>)
    at fulfilled (resolver.ts:226:1)
```

**To Reproduce**
run this app from docker: https://gist.github.com/dabit3/ba326e47e4882073bd6342dc1998fd16

**Expected behavior**
`await ceramic.did.authenticate()` works without exception

**Screenshots**
![image](https://user-images.githubusercontent.com/97550120/149002144-5ce6efc6-e23b-41f3-a365-c5a060a010a5.png)

**Ceramic versions** 
"@ceramicnetwork/http-client": "^1.5.6",
"ethers": "^5.4.4",
"dids": "^2.4.3",
"@3id/connect": "^0.2.5",
"@ceramicnetwork/3id-did-resolver": "^1.4.15",
"@ceramicstudio/idx": "^0.12.2"

**Machine, OS, browser information (please complete the following information):**
macos 11.6.2, m1 chip, 
docker with `node:current-alpine`, 
browser: brave 1.34.80 Chromium: 97.0.4692.71

**Additional context**

**Comment by Sterahi** [comment]
Hello @client03 have you tried doing the following on line 60 (based on the gist linked above)
```
await did.authenticate()
await ceramic.sestDID(did)
```
the rest of the code looks solid but if the above doesn't solve the problem I can try to set it up locally & see what I can find :)

**Comment by Sterahi** [comment]
Hey @client03 if this is running in a Create React App we've been having some notable issues with it and currently, we're debugging the underlying cause.

**Comment by client03** [comment]
Hello @Sterahi yep, the problem was with Create React App, I avoid this problem by migrating to next.js
Here is the same problems, that I've meet too with React: https://stackoverflow.com/questions/69960492/getting-compilation-errors-regarding-loaders-when-running-react-app

Thanks!
