### ISSUE TITLE
[Can't launch docker js-ceramic] could not detect network

### ISSUE THREAD

**Issue by Aornn** [ceramicnetwork/js-ceramic#2075]
# Description
Hi ! <br>
First of all, congrtulations for your project ! <br>
Here is my question, I tried to launch a node on the testnet with the provided docker image but the only thing I have is :
Ceramic daemon failed to start up:
```
Error: could not detect network (event="noNetwork", code=NETWORK_ERROR, version=providers/5.5.3)
    at Logger.makeError (/js-ceramic/node_modules/@ethersproject/logger/lib/index.js:199:21)
    at Logger.throwError (/js-ceramic/node_modules/@ethersproject/logger/lib/index.js:208:20)
    at JsonRpcProvider.<anonymous> (/js-ceramic/node_modules/@ethersproject/providers/lib/json-rpc-provider.js:517:54)
    at step (/js-ceramic/node_modules/@ethersproject/providers/lib/json-rpc-provider.js:48:23)
    at Object.throw (/js-ceramic/node_modules/@ethersproject/providers/lib/json-rpc-provider.js:29:53)
    at rejected (/js-ceramic/node_modules/@ethersproject/providers/lib/json-rpc-provider.js:21:65)
    at processTicksAndRejections (internal/process/task_queues.js:95:5) {
  reason: 'could not detect network',
  code: 'NETWORK_ERROR',
  event: 'noNetwork'
}
```
My Json conf is like this : 
```
{
    "anchor": {
        "ethereum-rpc-url": "https://ropsten.infura.io/v3/00d5671cacb54af4b121bad85583c08d"
    },
    "http-api": {
        "cors-allowed-origins": [
            ".*"
        ]
    },
    "ipfs": {
        "mode": "remote",
        "host": "http://172.17.0.2:5011"
    },
    "logger": {
        "log-level": 0,
        "log-to-files": true
    },
    "network": {
        "name": "testnet-clay"
    },
    "node": {},
    "state-store": {
        "mode": "fs",
        "local-directory": "/root/.ceramic/statestore"
    }
}
```

The ip host is my ipfs-deamon docker. Launch like this : 
`docker run -d -p 4011:4011 -p 5011:5011 -e CERAMIC_NETWORK=testnet-clay --name ipfs-daemon ceramicnetwork/ipfs-daemon:latest`

So i don't understand why I have this error ? Does anyone has the same on test net ?
I just want to clarify that the infura link is my own node

Thanks for all :)

**Comment by stbrody** [comment]
"ethereum-rpc-url" should be pointing to an Ethereum RPC endpoint, not to a Ceramic Anchor Service.

If you empty out the anchor config (anchor: {}) then your node will try to use the default ethers.js ethereum provider.  It's free but rate limited aggressively.  Should be enough for basic testing, but if your node will be used heavily you might need to upgrade to a paid ethereum provider (or run your own ethereum node)

**Comment by Aornn** [comment]
OK I see, but as far as i know, this url : "https://ropsten.infura.io/v3/00d5671cacb54af4b121bad85583c08d" is an Ethreum RPC endpoint, right ? Or am I missing something ?

**Comment by stbrody** [comment]
Oh weird, sorry, in our issue tracking system the `ethereum-rpc-url` was showing as "https://cas-clay.3boxlabs.com".  I guess you updated the ticket in github but I was still seeing the original version.

I'm not totally sure what's causing the issue then, although from the stack trace it does appear to be from the node trying to reach the ethereum rpc endpoint.  Can you attach the full Ceramic node logs from startup?

**Comment by Aornn** [comment]
Ok ... Weird I have juste relaunch my docker compose and everythings to work fine. Maybe it was an issue with infura.
