### ISSUE TITLE
loadStream is not re-entrant

### ISSUE THREAD

**Issue by FrozenKiwi** [ceramicnetwork/js-ceramic#2353]
**Describe the bug**
When running multiple calls to loadStream in parrallel, only the tip document is returned.

See discussion here:
https://forum.ceramic.network/t/solved-how-to-load-prior-commits/117

**To Reproduce**
Execute the following script:
```
import { Core } from '@self.id/core'
import { TileDocument } from '@ceramicnetwork/stream-tile'
import type { JWE } from 'did-jwt';

const did = "did:3:kjzl6cwe1jw146vyxh3bf1l325qcb3b4rxnns181whfw1mezrpmgyia2mm2otzm";
const aliases = JSON.parse(`{
  "definitions": {
    "AccountDetails": "kjzl6cwe1jw149gym1m5qjzzqjdlupnsxivgeef9z6xjkc14ldbkgwag1cssryr"
  },
  "schemas": {
    "jwe": "ceramic://k3y52l7qbv1frxwvp66vqpcd046ju9ocvimye6htwucpg00h08nltj1fkns6p9ji8"
  },
  "tiles": {}
}`)
const core = new Core({ ceramic: 'testnet-clay', aliases});

export async function getOtherHistory() : Promise<JWE[]|null>{

  console.log(`Loading history for ${did}`);
  const { ceramic, dataModel, dataStore } = core;
  const definitionId = dataModel.getDefinitionID("AccountDetails");
  // The recordId is the stream defined by definition for this DID
  const streamId = await dataStore.getRecordID(definitionId!, did);
  if (!streamId)
    return null;

  const stream = await TileDocument.load(ceramic, streamId);
  const ids = stream.allCommitIds;
  console.log("All Ids:\n", ids.map(id => id.toString()).join('\n'));

  console.log(`Found ${ids.length} commits`);
  // TODO: do this with a multi-query instead
  const commits = await Promise.all(ids.map(id => ceramic.loadStream(id)));
  return commits.map(c => c.content as JWE);
}

const all = await getOtherHistory();
if (all) {
  for (const commit of all) {
    console.log(commit.ciphertext);
  }
}
```
You'll see 20 different instances of identical `ciphertext`

**Expected behavior**
About 20 different commits should be logged with unique ciphertext

**Screenshots**

**Ceramic versions** 
Latest

**Machine, OS, browser information (please complete the following information):**
Windows

**Additional context**

From the discussion:

Internally, streams are cached and the call to loadStream syncs stream to the given ID. Doing them all at once means that once complete, the single cache is still sync’ed on a single commit, and we get back X documents all referencing that single (tip) commit.

**Comment by stbrody** [comment]
Thanks for the report.  There does indeed seem to be a bug in the HTTP client.  We'll try to get a fix together for that ASAP

**Comment by stbrody** [comment]
This should be fixed in the recent release of Ceramic!
https://discord.com/channels/682786569857662976/759017171358580787/1053045899443568731
