### ISSUE TITLE
Add gateway mode option

### ISSUE THREAD

**Issue by oed** [ceramicnetwork/js-ceramic#240]
Add an option to run a ceramic daemon in "gateway mode". This turns of the following features:
* all pinning functionalty
* apply (applying a record to a document)

Note that we still allow the `create` method (create from genesis), since we need to be able to create account-link doctypes by only knowing the caip10 accountId.

**Comment by Schwartz10** [comment]
@oed why does running a deamon in gateway mode disable those features?

**Comment by oed** [comment]
Because the gateway mode is supposed to be read only. If you run a public facing node you might not want anyone to use it to store information.
