### ISSUE TITLE
Unsupported method: personal_sign

### ISSUE THREAD

**Issue by emmajane1313** [ceramicnetwork/js-ceramic#2645]
I'm building a nextjs app that uses wagmi hooks for most of the web3 front end calls. When setting up the ceramic account auth and trying to call 

```
await DIDSession.authorize(authProv, {
        resources: [`ceramic://*`],
        
      })
```

I keep getting the following error from alchemy upon request: 

`bad response (status=400, headers={"content-length":"173","content-type":"application/json"}, body="{\"jsonrpc\":\"2.0\",\"id\":42,\"error\":{\"code\":-32600,\"message\":\"Unsupported method: personal_sign. See available methods at https://docs.alchemy.com/alchemy/documentation/apis\"}}`

Is there a way to switch from `personal_sign` to ethers_sign ?

I am getting my signer and provider from wagmi and was previously receiving another bad request error when calling `await threeIDConnect.connect(auth)` but was able to solve this by using Eip1193Bridge on the wagmi provider response so it could be correctly read by threeId 

```
const ethersSigner = useSigner().data as Signer;
  const wagmiProvider = useProvider({
    chainId: 8001,
  });
  const provider = new Eip1193Bridge(ethersSigner, wagmiProvider);
 const auth = new EthereumAuthProvider(provider, address as string);
 const threeIDConnect = new ThreeIdConnect();
 await threeIDConnect.connect(auth)
```

I'm not sure if the above is related to the error I'm currently experiencing but any help on how I can get the `personal_signer` or circumnavigated is much appreciated :)

Here is the code the full code that's being run: 

 ```
const { address } = useAccount();
  const ethersSigner = useSigner().data as Signer;
  const wagmiProvider = useProvider({
    chainId: 8001,
  });
  const provider = new Eip1193Bridge(ethersSigner, wagmiProvider);
  console.log(ethersSigner)
  useEffect(() => {
    if (lensProfile && !client) {
      createAuthProvider();
    }
  }, [lensProfile]);

  const createAuthProvider = async () => {
    try {
      const auth = new EthereumAuthProvider(provider, address as string);
      const threeIDConnect = new ThreeIdConnect();
      await threeIDConnect.connect(auth)
      const accountId = await getAccountId(provider, address as string);
      const authProv = await EthereumWebAuth.getAuthMethod(provider, accountId);
      const session = await loadSession(authProv);
      const ceramic = new CeramicClient();
      ceramic.did = session.did;
    } catch (err: any) {
      console.error(err.message);
    }
  };

  const loadSession = async (authProv: AuthMethod): Promise<DIDSession> => {
    const sessionStr = getCeramicSession();
    let session: any;

    if (sessionStr) {
      session = await DIDSession.fromSession(sessionStr);
    }

    if (!session || (session.hasSession && session.isExpired)) {
      session = await DIDSession.authorize(authProv, {
        resources: [`ceramic://*`],
        
      });
      setCeramicSession(session);
    }

    return session;
  };
```

**Comment by zachferland** [comment]
Hi! would you mind opening the same issues in this repo instead - https://github.com/ceramicnetwork/js-did, related libraries are there and would allow us to track it better 

First there is no need to use 3idconnect AND didsession, they offer the same thing, an authenticated did to use with ceramic. We recommend using did-session (alone).

**Comment by emmajane1313** [comment]
just moved the issue over

**Comment by zachferland** [comment]
Thanks! closing here
