### ISSUE TITLE
Error: Cannot find module 'multiformats/basics' when running the ceramic daemon

### ISSUE THREAD

**Issue by Schwartz10** [ceramicnetwork/js-ceramic#272]
Coming from [here](https://github.com/ceramicnetwork/js-ceramic/pull/270/files#diff-7eaf8b719891ae17df60808af6b93563R10-R12)

Possible fix: require the cjs modules directly like you do in the [tests](https://github.com/ceramicnetwork/js-ceramic/pull/270/files#diff-87e86f9b49fc08836668e42d7b08e2aaR9-R10)

**Comment by simonovic86** [comment]
I tried building it and running the CLI. Also, I installed the CLI directly from npm and I can run it as well.

The node version that I have is `v14.9.0`. The fix that you suggested won't solve the issue, unfortunately.

**Comment by simonovic86** [comment]
@Schwartz10 what version of node are you running?

**Comment by Schwartz10** [comment]
@simonovic86 switching to node `14.9.0` seems to have fixed the issue!

**Comment by simonovic86** [comment]
@Schwartz10 awesome!
