### ISSUE TITLE
could not coalesce error, "method": "eth_chainId", "params": [  ] } }, "message": "'args.method' must be a non-empty string." }

### ISSUE THREAD

**Issue by moneyDev1111** [ceramicnetwork/js-ceramic#2847]
could not coalesce error, "method": "eth_chainId", "params": [  ] } }, "message": "'args.method' must be a non-empty string." } error when using the ethers js v6. is it possible to use ethers v6? why not?

**Comment by oed** [comment]
Are you using an [eip-1193](https://eips.ethereum.org/EIPS/eip-1193) provider?

**Comment by moneyDev1111** [comment]
> 

sorry for not providing the code. here it is.

	const getCeramicProvider= async () => {
		const web3Provider = new BrowserProvider(window.ethereum);

		const address = await (await web3Provider.getSigner()).getAddress();

		const ethereumAuthProvider = new EthereumAuthProvider(web3Provider.provider, address);
		await connect(ethereumAuthProvider);
	};

**Comment by oed** [comment]
@moneyDev1111 Try doing this instead:
```
const ethereumAuthProvider = new EthereumAuthProvider(window.ethereum, address);
```

**Comment by moneyDev1111** [comment]
@oed it worked! thank you, so the only thing I guees to concider is having to connect the providers "separately" but whatever I guess it should be fine. thanks again:)

**Comment by moneyDev1111** [comment]
maybe...)) 
![image](https://github.com/ceramicnetwork/js-ceramic/assets/75484297/5fee619a-505d-45b1-b022-62aa7db93d6a)
