### ISSUE TITLE
Install not working on Mac OSX

### ISSUE THREAD

**Issue by drbh** [ceramicnetwork/js-ceramic#307]
The installation process completes, but running the cli causes an error

```
npm i -g @ceramicnetwork/ceramic-cli
```

![Screen Shot 2020-09-16 at 10 28 19 AM](https://user-images.githubusercontent.com/9896130/93351180-64edff80-f807-11ea-8ede-f87d436e1963.png)

**Comment by simonovic86** [comment]
hi, thanks for the report! the latest CLI requires Node.js version >= `14`. What version are you running?

**Comment by drbh** [comment]
but it looks like the most recent version is included in the `package.json`...  https://github.com/ceramicnetwork/js-ceramic/blob/ad3ab8c3646e6981d072f26c9822a3e6ed6935fe/packages/ceramic-cli/package.json#L52

There seems to be a similar issue that another user has who's using the same Node version as me `v12.16.1` https://github.com/multiformats/js-multiformats/issues/34

Gonna update to node 12.18.4 and test again

**Comment by drbh** [comment]
Yep that did the trick 👍

my commands for reference:
```bash
node -v
# v12.16.1
npm install -g n
n stable # or sudo n stable depending on permissions structure
node -v
# v12.18.4
```

**Comment by simonovic86** [comment]
nice 🚀   I'm closing the ticket. Thanks!

**Comment by drbh** [comment]
hmmm it looks like you guys already added that work around - I wonder why it didnt work

https://github.com/ceramicnetwork/js-ceramic/blob/08bb247e5e97e526a23d1a7af1913fac722d4019/packages/ceramic-cli/src/ceramic-cli-utils.ts#L16

**Comment by simonovic86** [comment]
We opened a ticket for `multiformats` library. The [link](https://github.com/multiformats/js-multiformats/issues/34)
