### ISSUE TITLE
The jws block contains a request path (/ceramic-instances/2b3d0c902caa1fdade4e3756e8294746061505d54041e78603b4146c5b0d9eb1/api/v0/admin/modelData) that doesn't match the request (/api/v0/admin/modelData)

### ISSUE THREAD

**Issue by hrbustor** [ceramicnetwork/js-ceramic#3076]
# Description

Hi, I have encountered a problem. When I proxy the ceramic node, I add a prefix path to the request path, but the node will report a JWS error during the request. 
I want to know the purpose of this validation. Can this restriction be removed?

# Technical Information
1 curl request example: 
<img width="1889" alt="image" src="https://github.com/ceramicnetwork/js-ceramic/assets/7246465/db3773b3-3ea5-47c6-b4bc-5c5861f7971c">
2 the source code from js-ceramic:
<img width="1607" alt="image" src="https://github.com/ceramicnetwork/js-ceramic/assets/7246465/2799c027-fe36-4868-85f2-da3015699589">

**Comment by stbrody** [comment]
Conversation moved to forum post: https://forum.ceramic.network/t/the-jws-block-contains-a-request-path-ceramic-instances-2b3d0c90-api-v0-admin-modeldata-that-doesnt-match-the-request-api-v0-admin-modeldata/1437/2
