### ISSUE TITLE
Question: ceramic daemon stops, what data should persist upon restart?

### ISSUE THREAD

**Issue by Schwartz10** [ceramicnetwork/js-ceramic#313]
I noticed that I used ceramic to create a doc tree, and I use IDX to resolve that doc tree. When I restart the daemon, the IDX root doc content seems to be reset - is that by design?

**Comment by oed** [comment]
We should probably think though how this works further. Right now all documents that are pinned should persist when you restart the node.

**Comment by Schwartz10** [comment]
@oed why do you think my IDX content seems to disappear after restarting the daemon?

Seems like my schemas and definitions are still published tho

**Comment by oed** [comment]
Can you confirm that they are pinned?
Might be something wrong with the loading logic? @simonovic86
