### ISSUE TITLE
API healthcheck endpoint

### ISSUE THREAD

**Issue by zachferland** [ceramicnetwork/js-ceramic#335]
helpful in managed service context to have endpoint that only returns 200s when running and does not create any log output unless there is useful health metrics to be logged 

Also send this to discord if it's down

**Comment by valmack** [comment]
the good thing about pin ls is that if i fails we have a sense that something is wrong. but i'm not entirely sure that behavior is appropriate for this health check. what do you think?

**Comment by valmack** [comment]
I'm going to scope this down to that that js-ceramic is responding at all. Until we determine we need something more. If IPFS goes down I think the service goes down too so a simple "alive" should be fine for now.
