### ISSUE TITLE
Make isUnique default true

### ISSUE THREAD

**Issue by oed** [ceramicnetwork/js-ceramic#366]
Currently the `isUnique` option of tile documents defaults to false. This means that if you create two documents with the same content they will get the same docID. In most cases this is not really desired, when we create a new document that document should be unique. So by default the `isUnique` option should be true. This still allows tiles to be created in a non unique way by setting the option to false.

Make sure to also update IDW with the 3ID creation.

**Comment by stbrody** [comment]
> Make sure to also update IDW with the 3ID creation.

What needs to be updated in IDW?  I would think that changing the default in js-ceramic would automatically change the behavior of IDW, and since I imagine we would indeed want to default to isUnique:true when creating 3IDs, is there actually anything to change there?  @oed

**Comment by oed** [comment]
I don't think anything needs to be chanced actually. I anticipated this change and isUnique is set to false already where needed 👍
