### ISSUE TITLE
Include chain-id in genesis header

### ISSUE THREAD

**Issue by oed** [ceramicnetwork/js-ceramic#368]

**Comment by stbrody** [comment]
So, I'm not actually sure there's a way to tell the chainId at document creation time currently?

The js-ceramic instance is configured with a URL for the CAS, but there's no way to know from that which chain the anchor service is configured with.  We could add an RPC to the configured anchor service to get what chain *its* configured with, but the anchor service itself currently gets [a piece of the chain ID](https://github.com/ceramicnetwork/ceramic-anchor-service/blob/develop/src/services/blockchain/ethereum/ethereum-blockchain-service.ts#L77) from the transaction response (namely whether it wound up connected to ropsten or mainnet).  Is there a way for the CAS to tell whether its connected to mainnet (chainid "eip155:1") or ropsten (chainid "eip155:3") from the URL it's configured with?  And more generally, is this the right approach you had in mind @oed?  Having js-ceramic query the CAS to fetch the chainId it was configured with?  Can we do it once at js-ceramic startup, or do we need to be concerned about the CAS getting reconfigured while we're running, and thus need to ask the CAS each time we request an anchor what chain it will be anchored on?

CC @simonovic86

**Comment by stbrody** [comment]
I sort of wonder if this ticket is even worth it?  Do we actually want to enforce that each document can only be anchored on a single blockchain for its entire lifetime?  What if there are some long-lived documents and the blockchain ecosystem changes enough over its lifetime that a new blockchain becomes appealing to use for anchoring - why shouldn't the document controller be able to change what blockchain is used?  If the chain being used is changing all the time it makes conflict resolution slightly less deterministic as now you're reliant on clock synchronization between the chains, but if changing anchor chains is a rare operation then I can't really imagine it causing a ton of problems in practice...

**Comment by oed** [comment]
So the way I imagine the chain anchor enforcement working is like this:
1. Select blockchain (*chain 1*) to anchor and put it's chainId in the genesis record
2. Enforce that the given doc is always anchored to *chain 1*
3. If we want to anchor to a new chain make an update to the document that specifies *chain 2* chainId (this update needs to be anchored in *chain 1*)
3. All new anchors now needs to happen on *chain 2*

This provides both security and the ability to change which chain the document is anchored in. Another reason to include the chainId in the genesis record is that if the ceramic node has multiple anchor services it would know which one to anchor any particular document to.

It probably makes sense to add another http endpoint to get the chainId as you are suggesting. An CAS should definitely not be changing the chain it's using imo. 

Longer term there are two things that we'd want to do:
* Have a "ServiceDocument" for CAS. A Document which describes the service offered by CAS, including the expected chainId. This is part of the longer term vision where ceramic serves as a metadata layer for a decentralized index of microservices.
* Request anchors client side (in http-client for example), this could reduce the need for larger nodes to request anchors (might add other complexities though, but worth considering)

**Comment by stbrody** [comment]
This depends on https://app.zenhub.com/workspaces/3box-labs-5b37f0a38968796fbdda5e06/issues/ceramicnetwork/ceramic-anchor-service/135

**Comment by stbrody** [comment]
This depends on https://github.com/ceramicnetwork/ceramic-anchor-service/issues/135

**Comment by stbrody** [comment]
This ticket will only add the chain id to the document metadata and require it to be present in the genesis record.  It will not change the update rules at all to enforce what chain updates get anchored in.  I filed https://github.com/ceramicnetwork/js-ceramic/issues/490 for the update rules enforcement change.

**Comment by stbrody** [comment]
It's not totally clear to me whether it makes more sense for `chainId` to live in the metadata, or top-level in the genesis record alongside `unique`.  On the one hand, metadata thus far is all for user-provided information, whereas the `chainId` will be added by the system.  On the other hand, we will eventually want to be able to update the `chainId` and currently we don't have an API for updating parts of a document that are neither its `content` nor its `metadata`.

I guess it probably makes the most sense for this to be in 'metadata' and we can just throw an error if the user ever provides it manually.  @oed @simonovic86

**Comment by oed** [comment]
I don't think `chainId` will always be added by the system. A dev might want to explicitly set it. Having it in metadata also allows anyone to inspect which chain the document is anchored in easily.
As for the error, we should only throw it if it's provided and the node doesn't support that chain.
