### ISSUE TITLE
Use new Update message

### ISSUE THREAD

**Issue by oed** [ceramicnetwork/js-ceramic#370]
Should be in the spec. Might need to be more detailed specs.

**Comment by stbrody** [comment]
Should switch to the new UPDATE message as specified in [CIP-71](https://github.com/ceramicnetwork/CIP/blob/master/CIPs/CIP-71/CIP-71.md) as part of this.

**Comment by stbrody** [comment]
Fixed by https://github.com/ceramicnetwork/js-ceramic/pull/542
