### ISSUE TITLE
Rename packages (remove ceramic prefix)

### ISSUE THREAD

**Issue by oed** [ceramicnetwork/js-ceramic#372]
Right now packages are named with a ceramic prefix, e.g. `@ceramicnetwork/ceramic-core`. This is quite redundant, we should remove the prefix on all packages that have them. E.g. `@ceramicnetowrk/core`.

**Comment by stbrody** [comment]
Renaming the directories and changing the names in the package[-lock].json files is straightforward, but should I also be trying to handle publishing the new packages and removing the old package names from the global npm registry as part of this?  If so, I'd probably want someone who's done it before to watch what I do so I don't actually break the package system... @oed @PaulLeCam @simonovic86

**Comment by stbrody** [comment]
Note to self: as part of this the "doctype-account-link" package should be renamed to "doctype-caip10-link"

**Comment by PaulLeCam** [comment]
Publishing is a bit tricky as we're using [lerna](https://github.com/lerna/lerna) that makes a mess with releases if anything goes wrong so it might be safer to sync with @simonovic86 about this.
Regarding removing old packages, it's not possible to really remove them but we can [deprecate](https://docs.npmjs.com/cli/v6/commands/npm-deprecate) them once the new packages are published.
