### ISSUE TITLE
Rename "account-link" doctype to "caip10-link"

### ISSUE THREAD

**Issue by oed** [ceramicnetwork/js-ceramic#411]
The account-link doctype in js-ceramic should be called caip10-link: https://github.com/ceramicnetwork/CIP/blob/master/CIPs/CIP-7/CIP-7.md

**Comment by stbrody** [comment]
My plan is to start by just updating the doctype within the ceramic codebase/protocol, but leave the npm package name "ceramic-doctype-account-link" alone for now.  As part of https://github.com/ceramicnetwork/js-ceramic/issues/372, I'll be updating the name of all the packages anyway, should I take that opportunity to rename this package to "caip10-link"?  Or do you think "account-link" is still a good name for this package, even after we've changed the doctype to "caip10-link"?  I guess it comes down to, will we ever have more types of account link doctypes, and if so, will they go in the same package or new packages?  @oed @simonovic86

**Comment by stbrody** [comment]
Actually, I see that the CIP-7 description linked above refers to a doctype-caip10-link package, so I will go ahead and plan to change the package name, but still defer that to #372

**Comment by oed** [comment]
Makes sense @stbrody 👍
