### ISSUE TITLE
Make sure schema is always stored with a version

### ISSUE THREAD

**Issue by oed** [ceramicnetwork/js-ceramic#413]
When a schema is set in the metadata property of a document it will be enforced that the content of that document conforms to this schema. Now if the schema is updated old updates of a document might become invalid. To get around this problem the document should have the schema DocID to be set to include the version of the schema. If the version is included already, then just use that version. If not, use the most recent version.

**Comment by stbrody** [comment]
I wrote some basic tests of the current behavior and I thought it might be nice to write down the current behavior for posterity.

Currently, if you update a schema document and that update causes existing documents associated with that schema to no longer be conformant, loading those documents will still work fine.  There doesn't seem to be any schema enforcement at document load time.  When updating document contents, you always have to continue to specify the document metadata (and therefore the schema) along with each update.  So if you try to update a document that is no longer conformant to its currently referenced schema document, the behavior depends on what schema you specify in the update.  If you specify just the docID of the schema doc, and new content that is conformant with the old version but not the current version, the update will fail.  If you explicitly specify the old version of the schema document, however, the update can succeed (and the schema link stored in the document will be updated to reference the specific version of the schema document specified).

So it sounds like this ticket does not change the set of updates that are possible in any way, it just changes the behavior if you have code that forms updates to a document by copying the schema field of the metadata object of the existing version of that document.  For code that is specifying the schema docID in updates manually this ticket will have no effect on the resulting behavior at all.

**Comment by stbrody** [comment]
@oed, I'm not totally convinced this change makes sense?  It's already possible to specify a schema version when assigning a schema to a document, if you want the document to be tied to a specific version of a schema.  It seems like some users might want to be able to choose whether their document should conform to the most recent version of the schema or be set to a specific version, rather than forced into having it always set to a specific version

**Comment by oed** [comment]
Thanks for the through review of the current functionality @stbrody. Turns out it works differently than I imagined.
My assumption had been that the schema would be verified each time a record was applied. That would mean that if the schema changed it might break old documents since the old records would no longer be valid. Turns out it's much more loose. However I'm still wondering what happens if the schema validation fails after the last record has been applied? Or is validation only happening when we update the document locally?

The idea behind this story assumes this more strict interpretation of schema validation. Do you think it makes sense in this case?

**Comment by stbrody** [comment]
https://github.com/ceramicnetwork/js-ceramic/pull/459 includes tests that demonstrate the existing behavior pretty well (as well as a fix for the metadata being thrown out issue I brought up in standup today).

As far as I can tell the schema validation is only happening locally when performing an update.  @simonovic86 suggested on the standup call though that perhaps schema enforcement does happen during document loading, but only via one path?  I'll have to defer to him on that one, I'm just speaking to the behavior I'm seeing from the tests I linked above.

If we think that schema enforcement *should* be happening any time a document is loaded, then that's something else we might have to fix, independent to the discussion about whether we always store schemas with a version.

**Comment by oed** [comment]
Well if enforcement *should* happen (let's discuss on thursday), then we *need* to always store schema with version.
