### ISSUE TITLE
Request timeouts

### ISSUE THREAD

**Issue by PaulLeCam** [ceramicnetwork/js-ceramic#418]
If a request is being made for a resource that doesn't exist on the network, the request seems to just hang indefinitely (or being raised by the proxy or test runner).

I think there are 2 types of timeouts we could support:
- On the node side, timing out because the resource might not exist, and returning an error to the client.
- In the client, supporting optional timeouts provided by the apps/libraries, that would also cancel the requests to the server.

**Comment by PaulLeCam** [comment]
We could use a lib like https://github.com/jacobheun/timeout-abort-controller or similar logic to handle abort signals in the client

**Comment by valmack** [comment]
@stbrody relevant since we talked about this today ^

**Comment by stbrody** [comment]
> We should also consider using a global timeout on the ipfs client as we do in CAS here https://github.com/ceramicnetwork/ceramic-anchor-service/pull/154/files#diff-e508c756ae445913263b02e629df115d9409df726a612a5dc4e1a04d6857ab3e

That seems likely to be the quickest/easiest way to get some basic protection in place we can act on.  I'm for it
