### ISSUE TITLE
Run ceramic on different pubsub topics based on environment

### ISSUE THREAD

**Issue by valmack** [ceramicnetwork/js-ceramic#438]

**Comment by valmack** [comment]
@simonovic86 @oed I don't have a great sense of how straightforward this is. Would be great to get your input

**Comment by simonovic86** [comment]
@valmack `js-ceramic` has support for providing the pubsub topic which will be used. We should deploy Ceramic with different pubsub topics based on the environment. @oed does that make sense?

**Comment by oed** [comment]
yeah, we should maybe standardize or document which topics are being used for what somewhere?

**Comment by michaelsena** [comment]
Is this for the network, i.e. Clay and Mainnet?

**Comment by simonovic86** [comment]
@michaelsena yep, and other environments, too (dev, etc.)

**Comment by oed** [comment]
Current topic: `/ceramic/` (something like it)
