### ISSUE TITLE
Document garbage collection

### ISSUE THREAD

**Issue by oed** [ceramicnetwork/js-ceramic#442]
- implement a periodic cleaner for `in-memory` docs store
- store versions separately from base docs.

**Comment by stbrody** [comment]
> * implement a periodic cleaner for `in-memory` docs store

Should this be a periodic cleaning job, or a fixed-size LRU cache?  I imagine the latter would give more consistent/predictable behavior.

**Comment by simonovic86** [comment]
@stbrody @oed fixed-size LRU cache makes sense 👍
