### ISSUE TITLE
Decide and maybe implement binary encoding on DocIDs and CIDs in records

### ISSUE THREAD

**Issue by oed** [ceramicnetwork/js-ceramic#444]
Do some pre processing before putting the record `data` and `header` into the ipfs dag:
* convert `ipfs://<cid>` to a CID instance
* convert `ceramic://<docid>` to a uint8array instance

When pulling the data from the dag convert in the opposite direction

**Comment by stbrody** [comment]
@oed is the "decide" part still part of this?  If so, what are the pros/cons/general context around making that decision?

**Comment by oed** [comment]
I think we should just have another discussion in the next tech sync. But I think it's very likely that we'll do this.

**Comment by stbrody** [comment]
I forgot to bring this up in our mindmeld today.  Should I just go ahead and do it, or do you still think this is worth deciding to do as a team? @oed

**Comment by oed** [comment]
Feel free to go ahead @stbrody

**Comment by stbrody** [comment]
@oed, are you suggesting that we scan the content provided by the user for strings matching the format `ipfs://[...]` and `ceramic://[...]`?  Modifying the user-provided content out from under them seems fishy IMO.  It also raises questions about how deep we should look - do we only consider top-level fields, or fields in subobjects and arrays also?  What about larger strings that contain ipfs or ceramic link substrings within them?  Doing this for the parts of the records that we control, like the schema document links or log links makes sense, but scanning arbitrary user data for anything matching a pattern makes less sense to me.

CC @simonovic86

**Comment by oed** [comment]
Yeah this is more of an optimization for url's which we think are going to be common. It only makes sense to do on values in objects where the entire string is the url. The main idea would be to go though the entire object and check each property if the value is a string and matches, then convert. I guess it could make sense to only do it for certain places like the schema, but that also feels a bit arbitrary?
Doing this on substrings wouldn't make sense.

**Comment by PaulLeCam** [comment]
I think we should be cautious about doing changes to the schemas provided by users if there's any chance the conversion could lose information.
For example we could have a schema encoding a DocID as a base64 URL, being converted to binary by our logic, and then decoded to a base36 DocID URL when loaded, which could accidentally break expectations from the schema author (such as diffs and validation).

**Comment by oed** [comment]
@PaulLeCam schema validation happens one layer above. This would happen just before you put the json-patch into an ipld block, and right after you pull the data from the blockstore.

**Comment by PaulLeCam** [comment]
Yes I mean if the conversion back from binary doesn't return the original DocID URL, it can create issues at the application level.
I wasn't thinking about validation at the Ceramic level but for example if an app uses the schema for its own form inputs validation.

**Comment by stbrody** [comment]
Okay, so you're imagining iterating over the entire document contents, including sub-objects, and checking if the value is an exact match for an ipfs or ceramic URL?  I suppose we know the exact character length for all such URLs so we should ignore strings that start with a URL prefix but have more stuff afterwards.  What about array fields?  For arrays of strings should we check and replace each string?  And for arrays of objects should we recursively check all the objects in the array?

What exactly is the benefit of doing this binary encoding?  Slightly smaller number of bytes in the record in IPFS?  Is there anything else?  Seems like potentially a lot of complexity for not much value?

**Comment by oed** [comment]
Good point @PaulLeCam I had not thought about that. I think that is not going to happen frequently but definitely something that can happen.

@stbrody yeah this is mostly an optimization. If we feel it's not worth the added complexity we should not do it.

**Comment by PaulLeCam** [comment]
I agree there's limited value doing binary encoding just for CIDs and DocIDs, I think the main benefit would be for other kinds of binary data such as public keys, signatures and encrypted contents that are much more wasteful encoded as strings.

I think over time it would be way more efficient to use binary encoding all the way through (client - node - storage) and only converting to JS objects at the edge, maybe using something such as https://github.com/zandaqo/structurae#MapView but as this may not be compatible with our existing tools (like ajv for JSON validation), it could be significant refactoring.

**Comment by oed** [comment]
I would hesitate to adopt anything that moves us away from the IPLD data model. Not sure if this would be compatible or not @PaulLeCam?

**Comment by PaulLeCam** [comment]
I think IPLD supports different codecs so it's mostly about whether we can easily convert between structurae data types and [DAG-CBOR](https://specs.ipld.io/block-layer/codecs/dag-cbor.html#format) for example, might be worth spending some time trying it out!

**Comment by oed** [comment]
It does support multiple codecs, but using a different binary encoding than dag-cbor I don't think would benefit us that much. When you get data from the blockstore the output is always a js object.

**Comment by PaulLeCam** [comment]
Yes the libs provided by IPLD convert to JS objects but that's an implementation detail, no?
As long as we can provide a valid codec to encode/decode a block into DAG-JSON, I'd expect we should be able to use it as we want.

**Comment by oed** [comment]
That sounds like a huge lift tbh and would make us totally incompatible with IPFS. Right now we are also using json-patch which we would need to implement a replacement for. We can likely revisit this when we are looking at CRDT libs for data struct merging.

**Comment by PaulLeCam** [comment]
How would that make use incompatible with IPFS? If we're using a supported codec, it's all that matters for IPFS, no?
The difference would be purely on our side, handling binary structures rather than JS objects, which I agree would mean we couldn't use our current JSON schema tools without doing wasteful conversions so that would be a larger refactoring.

**Comment by oed** [comment]
IPFS expects data to be js objects in order to traverse multiple ipld blocks. I guess in theory we could have an internal representation using dag-cbor and then just put that directly into the blockstore, but I'm not sure how much we'd gain from that.

**Comment by PaulLeCam** [comment]
We'll mostly gain over storage size assuming we can fully benefit from encoding binary data in a binary format rather than as strings.
If IPLD block traversal requires to convert objects to JS that seems wasteful compared to binary but as it's already working this way I don't think that would change anything (IPFS would do the DAG-CBOR to JS conversion as it does now). Eventually though I think we could replace this logic by doing lookup over the binary data itself to increase performance.

**Comment by oed** [comment]
Maybe what we want here is the [advanced data layouts](https://specs.ipld.io/schemas/authoring-guide.html#advanced-data-layouts)? This  is still a fairly new concept in IPLD though.

**Comment by PaulLeCam** [comment]
Yes that seems useful to spec the DocID encoding, but for other kinds of binary data we can simply use the `Bytes` type anyways.
I don't think the problem is so much on IPLD's side but rather our usage of JSON schemas for validation, that doesn't support binary data.

Maybe an alternative for us would be to use custom objects like IPFS does for links with the `/` char, for example:
```js
{'\': {type: 'docid', bytes: [0, 12, 245, ...]}}
{'\': {type: 'binary', bytes: [0, 12, 245, ...]}}
```
So instead of walking through all the objects and "guessing" if a string is a DocID or other binary data, our JSON encoding would have to be explicit and the encoding algorithm simply would have to look for objects with a `\` (or any other char we pick) key?

**Comment by oed** [comment]
Yeah, that could make sense. Would this also happen on the top level then @PaulLeCam? 

Is this worth doing now, or are we fine with using url-strings for now?

**Comment by PaulLeCam** [comment]
Yes I think if we want to move forwards with such a format, we should define it in CIPs and use it in our schemas when possible.

**Comment by oed** [comment]
sounds good. Then let's close this and postpone such a CIP until after fire.
