### ISSUE TITLE
Increase polling interval for anchor records

### ISSUE THREAD

**Issue by simonovic86** [ceramicnetwork/js-ceramic#448]
- increase polling interval for anchor records (ceramic->CAS).

**Comment by stbrody** [comment]
Can we use long polling to make this smoother?

**Comment by simonovic86** [comment]
@stbrody the intervals between consecutive anchors could be quite large - a couple of hours.

**Comment by stbrody** [comment]
I see.  What polling interval were you thinking of going with?

**Comment by simonovic86** [comment]
we should still decide on the anchoring interval for CAS (6, 12 times per day) so it makes sense to be correlated to that.
