### ISSUE TITLE
3IDs created using 3ID connect can't be loaded on local node

### ISSUE THREAD

**Issue by PaulLeCam** [ceramicnetwork/js-ceramic#482]
3ID connect uses the `ceramic.3boxlabs.com` node to store the 3ID and IDX docs.
When trying to use IDX with a local node (running `ceramic daemon`), the following cases often happen:
- the 3ID can't be resolved
- the 3ID is resolved but does not contain the IDX document URL (which is added by an update to the DID)

Steps to reproduce:
1. run the ceramic daemon
1. install the IDX CLI: `npm i -g @ceramicstudio/idx-cli`
1. create a 3ID in the Web playground (https://ceramicstudio.github.io/web-playground/) - the DID will be logged in the console once connected
1. run `idx index:check <created DID> --ceramic=https://ceramic.3boxlabs.com` - it should work as expected
1. run `idx index:check <created DID> --ceramic=http://localhost:7007` - it should fail at some point

**Comment by simonovic86** [comment]
@PaulLeCam @oed this should be related to [489](https://github.com/ceramicnetwork/js-ceramic/issues/489).

I guess that because of the disabled DHT in IPFS the local Ceramic node is not able to get all the updates.

**Comment by PaulLeCam** [comment]
@simonovic86 I tried again running the CLI v0.13.2 but I still see the same behavior, the request to load the DID document hangs until it finally throws `FetchError: request to http://localhost:7007/api/v0/state/ceramic/kjzl6cwe1jw1466g3bpurjpuighjl1o4z0ne1e3yt364h8zoqgdizyd9r9qsndi failed, reason: socket hang up
    Code: ECONNRESET`

**Comment by simonovic86** [comment]
@PaulLeCam the document that I got from `https://ceramic.3boxlabs.com` had more content - the local one had only the genesis. How's the document being created and when?

**Comment by PaulLeCam** [comment]
It was probably created right before being accessed but that's the core of the problem: the app authenticates the user using 3ID connect (connecting to `https://ceramic.3boxlabs.com`), then gets the DID and tries to interact with IDX (connecting to `http://localhost:7007`) but this request simply hangs.

I'm just behind a home router provided by the ISP, nothing fancy so if it comes from this it's likely a common issue.

**Comment by zachferland** [comment]
looks like more work to do here still, not following steps above, but similar. 

Issues recently resolved at ipfs/infra level should be able to support this now, but still does not behave as expected.

local ceramic node and http client reliably resolve the genesis record (created on infra node), but must not be getting most recent tips through pubsub, therefore it does not resolve the most recent updates. Same happens even when local ceramic node directly connects to our infra ipfs node.

**Comment by oed** [comment]
Ok, thanks for explicitly confirming @zachferland. This should be a high priority to fix!

**Comment by oed** [comment]
I believe this should be fixed now? @zachferland @PaulLeCam

**Comment by PaulLeCam** [comment]
Yes I just checked that works for me
