### ISSUE TITLE
Provide a way to update the chainId for an existing document

### ISSUE THREAD

**Issue by stbrody** [ceramicnetwork/js-ceramic#500]
Provide proper logic to swap what chain a document is configured to be anchored in.  The update specifying the new chainid should be anchored in the old chain, and then all future updates get anchored in the new chain.  See [this comment](https://github.com/ceramicnetwork/js-ceramic/issues/368#issuecomment-724598919) for more details

**Comment by oed** [comment]
I think this should be postponed to after Fire since it's not that critical.

**Comment by stbrody** [comment]
We no longer encode chainid in the document metadata so this is no longer relevant.  Supporting multiple blockchains for anchoring on the ceramic mainnet will be a much larger undertaking if/when we decide to do it
