### ISSUE TITLE
IPFS API issues

### ISSUE THREAD

**Issue by simonovic86** [ceramicnetwork/js-ceramic#545]
There are issues with the `IPFSApi` imports. We need to fix them and possibly create a hotfix for deprecated packages.

```
node_modules/@ceramicnetwork/ceramic-common/lib/context.d.ts:5:25 - error TS2307: Cannot find module './declarations' or its corresponding type declarations.

5 import { IPFSApi } from "./declarations";
                          ~~~~~~~~~~~~~~~~

node_modules/@ceramicnetwork/ceramic-common/lib/utils/doctype-utils.d.ts:2:25 - error TS2307: Cannot find module '../declarations' or its corresponding type declarations.

2 import { IPFSApi } from "../declarations";
                          ~~~~~~~~~~~~~~~~~
```

**Comment by oed** [comment]
I believe js-ipfs made some changes to how types are generated. Perhaps we can check if the Ipfs type just works now?

**Comment by simonovic86** [comment]
> I believe js-ipfs made some changes to how types are generated. Perhaps we can check if the Ipfs type just works now?

@oed I checked but there is no easy way how to import the IPFS API still.

**Comment by oed** [comment]
Bummer.
