### ISSUE TITLE
Unhandled Rejection (Error): Cannot read property '0' of undefined - Ceramic Daemon Issue

### ISSUE THREAD

**Issue by ajumathewthomas** [ceramicnetwork/js-ceramic#553]
Hi All,

I am getting the below error message while I tried to run the ceramic daemon

"×
Unhandled Rejection (Error): Cannot read property '0' of undefined
▼ 2 stack frames were expanded.
(anonymous function)
F:/New folder/src/utils.ts:13
fulfilled
http://localhost:3000/static/js/0.chunk.js:2750:24
▲ 2 stack frames were expanded."

Please find the screenshot for further reference

OS version: Windows 10 x64
![Capture](https://user-images.githubusercontent.com/50171118/100517675-65fdbe80-31b2-11eb-9511-1807b0533c29.JPG)

Node version : v14.15.0
npm version : 6.14.8

**Comment by oed** [comment]
Hey, can you try using `@ceramicnetwork/cli` instead which is the newer package!

**Comment by oed** [comment]
hey @ajumathewthomas, did you try to use the updated package?

**Comment by ajumathewthomas** [comment]
> hey @ajumathewthomas, did you try to use the updated package?

Hey yes, I did. It worked.. sorry for the delay in replying. not much active here nowadays...

**Comment by oed** [comment]
Great, thanks!
