### ISSUE TITLE
Clarify which js-ceramic APIs are public

### ISSUE THREAD

**Issue by stbrody** [ceramicnetwork/js-ceramic#554]
We should firm up our understanding as a team as to which APIs within the js-ceramic codebase are designed to be used by end-user developers who are building applications on top of Ceramic, and which APIs are just internal to implementing Ceramic itself.  After deciding this, we should record our decision in some way and make sure our public-facing documentation reflects these decisions accurately.

**Comment by PaulLeCam** [comment]
👍 Thanks for opening this issue, I agree it would be good to have a clear understanding of these APIs to better anticipate breaking changes.

Maybe that's out of the scope of this issue, but I think it would be nice to have support for update (= `loadDocument()` + `doc.change()`) and "pseudo-delete" (update to empty the contents maybe?) methods as part of these public APIs so we could easily implement a fetch-like client to interact with Ceramic.
That would notably help us support https://github.com/RangerMauve/p2p-fetch if we wanted to.
