### ISSUE TITLE
Improve behavior when an anchor gets performed in the middle of consecutive updates to a document

### ISSUE THREAD

**Issue by stbrody** [ceramicnetwork/js-ceramic#616]
Copied from https://github.com/ceramicnetwork/js-ceramic/issues/615:

Imagine one ceramic node performs multiple consecutive updates to the same document that each get squashed into the previous

Update 1: changes field 'A'
Update 2: changes field 'B', and also includes update 1's changes to field 'A'
Update 3: changes field 'C', and also includes update 1 and 2's changes to fields 'A' and 'B'

what if while the node is creating and publishing update 3, update 2 gets anchored? In that case the behavior will be that update 3 will eventually get discarded as it will conflict with the anchor record built on top of update 2.

This is a pretty poor user experience.  Ideally update 3 would get "rebased" on top of the anchor record, rather than silently dropped with no notification to the developer/end user.

**Comment by stbrody** [comment]
FYI @oed @PaulLeCam @michaelsena @simonovic86.

I'm not really sure where to put this ticket so it doesn't get lost.  Definitely seems like something we'll need to revisit at some point, but it's not totally clear when or as part of what... @oed

**Comment by stbrody** [comment]
Note that this would be a problem even if we didn't squash updates.

**Comment by oed** [comment]
> Note that this would be a problem even if we didn't squash updates.

Yeah, I think this is something that would only be solved with a more sophisticated CRDT doctype.

**Comment by stbrody** [comment]
Yeah, I guess rebasing and re-applying the update won't really work since the new record would need to be re-signed.  We could however provide a better mechanism for notifying developers if a change gets rejected.  Perhaps a callback for each record that gets called if that record gets rejected by conflict resolution.  At least that way updates wouldn't be silently disappearing out from under people
