### ISSUE TITLE
Remove IPFS dependency from Ceramic common

### ISSUE THREAD

**Issue by simonovic86** [ceramicnetwork/js-ceramic#631]

**Comment by simonovic86** [comment]
There are new releases of IPFS repositories which should be revisited:
-`ipfs-core@0.3.1`
-`ipfs-http-client@48.1.3`.

**Comment by stbrody** [comment]
We should just depend on the IpfsApi type, not the entire ipfs implementation.  This depends on a proper official IpfsApi type existing within js-ipfs

**Comment by ukstv** [comment]
I guess, this can be freely closed. Common depends on ipfs types only, in dev mode.
