### ISSUE TITLE
Update log rotation in js-ceramic

### ISSUE THREAD

**Issue by valmack** [ceramicnetwork/js-ceramic#645]
Users running nodes should choose their own archiving strategy but we can allow a cli option for some default rotation using [rotating-file-stream](https://www.npmjs.com/package/rotating-file-stream#rfscreatestreamfilename-options). As we do in cas.

**Comment by stbrody** [comment]
This depends on https://github.com/ceramicnetwork/js-ceramic/issues/869, and will mostly be about surfacing new config options to expose the capabilities from the new logging framework

**Comment by stbrody** [comment]
@valmack - is there actually anything to do here? The CAS doesn't actually expose any of the `RotatingFileStream` options other than the file path.  Maybe that's enough to get started with, and we can expose more if/when users ask for it?

**Comment by valmack** [comment]
@stbrody completely agree. this is closed by your merges
