### ISSUE TITLE
CLI package still throws memory leak errors

### ISSUE THREAD

**Issue by Schwartz10** [ceramicnetwork/js-ceramic#661]
Running `@ceramicnetwork/cli 0.16.2`, I still see:

```
(node:35283) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 close listeners added to [Socket]. Use emitter.setMaxListeners() to increase limit
(node:35283) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 close listeners added to [Socket]. Use emitter.setMaxListeners() to increase limit
(node:35283) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 close listeners added to [Socket]. Use emitter.setMaxListeners() to increase limit
(node:35283) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 finish listeners added to [Socket]. Use emitter.setMaxListeners() to increase limit
(node:35283) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 error listeners added to [Socket]. Use emitter.setMaxListeners() to increase limit
```

This causes the daemon to sloooooow down and eventually stop responding to requests (this time, it seems to cause timeout errors)

**Comment by stbrody** [comment]
Hi @Schwartz10, any details you could share about how you're running tests, what the tests do, how long they run, how many distinct documents they create/load, how many distinct updates they create/load, etc. would be appreciated and could help with diagnosing what's happening here!

**Comment by stbrody** [comment]
Given that we don't yet have document garbage collection (https://github.com/ceramicnetwork/js-ceramic/issues/442), I'm wondering if there's any way this issue could be as simple as their test creates a lot of documents and those documents never get removed from memory, so memory usage just keeps growing over the lifetime of the test...

**Comment by stbrody** [comment]
@Schwartz10, you said on discord that the slowness seems somewhat sporadic - is the memory growth constant and only the perf hit is sporadic?  Or is the memory growth sporadic and the slowdown is well correlated to the memory growth?  Or some other combination?

**Comment by Schwartz10** [comment]
Hey @stbrody I will leave a more detailed response in this ticket over the next few days so you can diagnose the issue further

**Comment by Schwartz10** [comment]
@stbrody Not sure about this, but it could be related to so many `request timeout` errors we get in the CLI? This definitely starts happening once a few docs have been set?

**Comment by oed** [comment]
cc  @valmack is this relevant to the issues we are seeing with our ipfs infra perhaps?
