### ISSUE TITLE
Restarting node causes it to forget about document tips

### ISSUE THREAD

**Issue by stbrody** [ceramicnetwork/js-ceramic#665]
Steps to reproduce:
First, start ceramic daemon, then:
```
> alias ceramic
alias ceramic='node packages/cli/bin/ceramic.js'
> ceramic create tile --content '{ "foo": "bar" }'
DocID(kjzl6cwe1jw146zpd28f4zcw0i754fvcvfdfmubxvm5r8vpmeu2vsqy3qz90dtt)
{
  "foo": "bar"
}
> ceramic show kjzl6cwe1jw146zpd28f4zcw0i754fvcvfdfmubxvm5r8vpmeu2vsqy3qz90dtt
{
  "foo": "bar"
}
> ceramic change kjzl6cwe1jw146zpd28f4zcw0i754fvcvfdfmubxvm5r8vpmeu2vsqy3qz90dtt --content '{ "foo": "baz" }'
{
  "foo": "baz"
}
> ceramic show kjzl6cwe1jw146zpd28f4zcw0i754fvcvfdfmubxvm5r8vpmeu2vsqy3qz90dtt
{
  "foo": "baz"
}
```
Now restart the ceramic-daemon and then:
```
> ceramic show kjzl6cwe1jw146zpd28f4zcw0i754fvcvfdfmubxvm5r8vpmeu2vsqy3qz90dtt
{
  "foo": "bar"
}
```

I would have expected the state store to remember the current tip and load it correctly even across restarts

**Comment by stbrody** [comment]
I suspect the issue is that we only actually update the pin store if the document is *already* in it: https://github.com/ceramicnetwork/js-ceramic/blob/6a67f49c1ec407e756e65df00c73ee42bfc1ff54/packages/core/src/document.ts#L279-L283

**Comment by stbrody** [comment]
This presumably would have been discovered as part of https://github.com/3box/ceramic-infra/issues/178.  Perhaps these tickets can be done together, to both fix the behavior and put a regression test in place

**Comment by stbrody** [comment]
Might make sense for @simonovic86 to pick this up and do it alongside https://github.com/3box/ceramic-infra/issues/178?  @oed

**Comment by oed** [comment]
@stbrody The ceramic node is only expected to remember the documents that are pinned right?

**Comment by stbrody** [comment]
Ah yeah, I guess I misunderstood how the pinning API works.  I didn't realize you have to explicitly opt-in on a document-by-document basis.  I guess this works as designed.  We may want to add a mode where all documents get pinned by default, but that can be a separate feature request.
