### ISSUE TITLE
Add config option to CeramicAPI to auto-pin any created streams

### ISSUE THREAD

**Issue by stbrody** [ceramicnetwork/js-ceramic#676]
Also to consider as part of this - should this be the default behavior?

**Comment by stbrody** [comment]
Related to (but different from) https://github.com/ceramicnetwork/js-ceramic/issues/677

**Comment by stbrody** [comment]
@oed thoughts on making this the default behavior?  So Ceramic by default pins all created streams?  Is there a real use case for creating streams without pinning them, against a mainnet node?

**Comment by oed** [comment]
I think I would be fine with this.

**Comment by stbrody** [comment]
Added to "pinning optimizations" epic, not really because it's strictly part of that work, but because we probably wouldn't want to make this change until the perf issues with pinning are resolved.
