### ISSUE TITLE
Ensure that error messages propagate properly through the HTTP client

### ISSUE THREAD

**Issue by stbrody** [ceramicnetwork/js-ceramic#679]
errors thrown by the daemon and sent over the HTTP response don't get parsed and thrown properly by the HTTP client, so application code doesn't get useful error messages when using the http client.  We should fix (and test!) this

**Comment by oed** [comment]
Is this related to https://www.notion.so/threebox/Refactor-ceramic-daemon-server-866c34d484224022b7d3548e0391fd74 ?

**Comment by ukstv** [comment]
TBH, the HTTP-client endeavour seems more likely related to State Refactor, yet I can not imagine now how it can be started in parallel while maintaining compatibility.

**Comment by oed** [comment]
Maybe you can provide some more context here @stbrody ?

**Comment by stbrody** [comment]
Hmm... there are 4 tickets currently in the "clean up HTTP client" epic.  None of them seem directly dependent on the state refactor work to me.  Can you provide more details on what inter-dependency you see and are concerned about @ukstv?

This specific ticket does however seem to overlap with the "Refactor ceramic daemon server" epic that Joel links above

**Comment by ukstv** [comment]
Okay, let's start inter-dependency talk in appropriate #892

This one is all right to run.

**Comment by ukstv** [comment]
Well, almost allright. I mean, I expect right now an error to be exposed via traditional control flow. This should be. I'll check if it is true. What else is there to desire?

**Comment by PaulLeCam** [comment]
The APIs I implemented in https://github.com/ceramicnetwork/js-errors-utils were designed to support these cases with namespacing errors, keeping track of the stack and being serializable to JSON.

**Comment by stbrody** [comment]
This and https://github.com/ceramicnetwork/js-ceramic/issues/1153 are dupes of each other.  The other is a bit more specific in its description as to what the required work is, so closing this one in favor of that one
