### ISSUE TITLE
Documents created using the CLI don't have their content set

### ISSUE THREAD

**Issue by patriciac24** [ceramicnetwork/js-ceramic#691]
I follow the guide in the blog about  Building with Clay: Getting started with the Ceramic Network, when i create a document,try to reading or try to change the value of the content appears null. 

ceramic create tile '{ "Hello": "World!"}'
DocID(k2t6wyfsu4pg26k2tkb5rnwykk19twg0yvqyj7nf9c50hsedzqh0r6s653ebo0)
null
ceramic show ceramic://k2t6wyfsu4pg26k2tkb5rnwykk19twg0yvqyj7nf9c50hsedzqh0r6s653ebo0
null
ceramic state ceramic://k2t6wyfsu4pg26k2tkb5rnwykk19twg0yvqyj7nf9c50hsedzqh0r6s653ebo0
{
  "doctype": "tile",
  "content": null,
  "metadata": {
    "schema": null,
    "controllers": []
  },
  "signature": 2,
  "anchorStatus": "FAILED",
  "log": [
    "bafyreig4o6fqtehmjzyo4zvylu4j2dpljs727gwnlntrrh7tndifhn5jsa",
    "bagcqceraekqcidukh5itxxhhuycu7ryqbq6b7enpbyyn5du756edwgnu46mq"
  ],
  "next": {
    "content": null,
    "metadata": {
      "schema": null,
      "controllers": []
    }
  },
  "anchorScheduledFor": null
}

**Comment by stbrody** [comment]
When you initially create the document, you need to use the `--content` flag to set the content.  So try changing the first line of your example to `ceramic create tile --content '{ "Hello": "World!"}'`

**Comment by patriciac24** [comment]
ceramic create tile --content '{ "Hello": "World!"}'
Unexpected token ' in JSON at position 0

**Comment by stbrody** [comment]
Hmm... that works for me.  Might be different character escaping rules between shells/terminals?  Can you try escaping the quotes or trying a different shell?

**Comment by michaelsena** [comment]
@patriciac24 are you using windows? If so maybe try something like this:
```
ceramic create tile --content "{ \"Hello\": \"World\" }"
```

**Comment by patriciac24** [comment]
ceramic create tile --content "{ \"Hello\": \"World\" }"
DocID(kjzl6cwe1jw148irg2bfelhxj3xyoro6sfeqiik8wj644up46y7zraimx3frg1s)
{
  "Hello": "World"
}

Success! Thanks and with other commands ?

**Comment by stbrody** [comment]
I don't think you should have any problems with the "show" or "state" commands, the issue is only when you need to provide JSON input, so when creating or updating documents.  Anytime you need to pass `--content` you should escape the json strings with full quotes just like you just did

**Comment by patriciac24** [comment]
Thanks for all!
