### ISSUE TITLE
Gateway mode should not include createDocFromGenesis

### ISSUE THREAD

**Issue by valmack** [ceramicnetwork/js-ceramic#703]
This endpoint is available when running ceramic as a gateway
```app.post(toApiPath('/documents'), this.createDocFromGenesis.bind(this))```

See https://github.com/ceramicnetwork/js-ceramic/blob/develop/packages/cli/src/ceramic-daemon.ts#L160-L179

But gateway mode should be readonly and `createDocFromGenesis` allows a doc to be created and potentially anchored

**Comment by oed** [comment]
The reason this is included is because we need to be able to load documents from only knowing the genesis record. This is useful when loading caip10-links for example. There you might only know an ethereum address and from that create the genesis record.
