### ISSUE TITLE
Updates to IDX doc do not make it back to IDX when checked from different provider (very similar to last bug)

### ISSUE THREAD

**Issue by Schwartz10** [ceramicnetwork/js-ceramic#715]
This is a very similar bug to the one we debugged today. The only difference is that _the IDX doc that we're setting already exists before beginning the flow_. Interestingly enough, I can't get the test to pass in the same way I did before (immediately calling `idx.get` with the same IDX provider to load the doc).

Remember how we had something like this:

```js
    await this._idx.set("permissions", {
        ...perms,
        [requesterDID]: doc.id.toString(),
    });
```

Which resolved correctly when calling:

```js
 console.log(await this._idx.get("permissions"))
```

But does not resolve correctly when calling:

```js
// load IDX with a different provider
const cer = new CeramicClient()
const idx = new IDX({ ... })
const permsA = await idx.get(
        "permissions",
        // use did of the original IDX did provider
        did
);
```

**The doc already exists, and I get the outdated doc back**

**Comment by oed** [comment]
I'm unable to replicate this issue locally. 
I wonder if it could be related to this somehow? https://github.com/ceramicnetwork/js-ceramic/pull/714

**Comment by Schwartz10** [comment]
The Ceramic HTTP Client caches documents, so when 2 HTTP clients exist with the same provider, and only one makes an update to a doc, checking that doc from the other HTTP client does not show the updated doc because the cached value is being used

**Comment by oed** [comment]
Should be fixed by https://github.com/ceramicnetwork/js-ceramic/pull/719 However I'm blocked from making a beta release of this right now.

**Comment by oed** [comment]
@Schwartz10 See #719 You should be able to test this with the alpha release
