### ISSUE TITLE
Restarting ceramic daemon causes unpinned IDX docs with updates to lose their updates

### ISSUE THREAD

**Issue by Schwartz10** [ceramicnetwork/js-ceramic#717]
- Create a ceramic doc (do not pin manually)
- Update ceramic doc (do not pin manually)
- Check state of doc (see that the next content is populated correctly)
- Shut down daemon
- Start up daemon
- Check state of doc (see that the next content is no longer populated).

Pinning the updated ceramic doc manually fixes this problem.

This populates to IDX (maybe IDX does pin updates?):

- IDX set a doc
- IDX get doc (it's there)
- restart daemon
- IDX get doc (`null`)

I do have the `autopin` option set to `true` when instantiating IDX instances (I believe this is default behavior anyways).

**Comment by oed** [comment]
This should be fixed by https://github.com/ceramicstudio/js-idx/pull/33 Can you confirm @Schwartz10 ?

**Comment by Schwartz10** [comment]
This does not appear to be fixed in IDX `0.5.2`, running daemon version `0.18.1`. 

We can create a new IDX reference doc with a custom definition, `get` it successfully, shut down the daemon, restart it, and then when we try to `get` the same IDX reference doc (from a new IDX instance of course, with a different DID provider), the content comes back as `null`. Will work on reproducing this in a minmal example
