### ISSUE TITLE
DocState should store inner CIDs for SignedCommit link records

### ISSUE THREAD

**Issue by stbrody** [ceramicnetwork/js-ceramic#730]
The document state log contains the CID of every record applied to a document.  But in the case of SignedRecords, there is an additional CID that is important to the document log: the `link` record that contains the payload of the actual data.  This leads [Document._findIndex](https://github.com/ceramicnetwork/js-ceramic/blob/c7561344c619f72a243d1f27978393830bf49f56/packages/core/src/document.ts#L374-L377) to need to load this `link` record for every signed record in the log when looking for a CID.  Given that `Document._findIndex` is used quite often as part of handling incoming tips, this results in a very real perf hit (I imagine, I haven't actually measured this directly).  If we cached both the outer SignedRecord and the inner 'link' record CIDs in the document state, all those checks could be done purely in memory without any network i/o, and I suspect this would give us a major perf improvement.

In addition to the perf improvement, this could be used to clean up and simplify a lot of code that has to have special case handling for SignedCommits in many different places.

**Comment by ukstv** [comment]
Hey, @stbrody may we close this one in favour of #1444 and #1445 ?

**Comment by stbrody** [comment]
It does seems likely that some combination of #1444 and #1434 probably remove the need for this, but given as there's still some open questions around #1434 and whether or not we can safely remove the checks on link CIDs from _findIndex, I'd like to leave this open at least until we've confirmed that.  If #1434 winds up removing the need to load link CIDs from _findIndex, then I think it'd be fine to go ahead and close this one out.

**Comment by stbrody** [comment]
Obsolete now due to https://github.com/ceramicnetwork/js-ceramic/issues/1434
