### ISSUE TITLE
versioning for pub/sub messages

### ISSUE THREAD

**Issue by stbrody** [ceramicnetwork/js-ceramic#738]
In order to be future-proof to future protocol changes, we should introduce a `version` property into our pub/sub messages, and error and refuse to process any messages with a version greater than what we currently support

**Comment by stbrody** [comment]
this might not be a single `version` field, but possibly 2 fields indicating a lower and upper bound version range that must overlap with the version of any ceramic instance that is processing the message

**Comment by oed** [comment]
I have the same response here as in https://github.com/ceramicnetwork/js-ceramic/issues/739
