### ISSUE TITLE
Versioning for records

### ISSUE THREAD

**Issue by stbrody** [ceramicnetwork/js-ceramic#739]
In order to be future-proof to future protocol changes, we should introduce a `version` property into our document records, and error and refuse to process any records with a version greater than what we currently support

**Comment by stbrody** [comment]
related to https://github.com/ceramicnetwork/js-ceramic/issues/738

**Comment by stbrody** [comment]
this might not be a single `version` field, but possibly 2 fields indicating a lower and upper bound version range that must overlap with the version of any ceramic instance that is processing the message

**Comment by oed** [comment]
I think that the current version is simply 0, when we need to make a breaking change we introduce a new property `v` which is set to `1`.

**Comment by stbrody** [comment]
> I think that the current version is simply 0, when we need to make a breaking change we introduce a new property `v` which is set to `1`.

Yep, agreed.  The thing we need to do now is check for the 'version' field and error if it's set

**Comment by oed** [comment]
Do we really need to do that? Seems like old nodes would break with an introduction of a new format anyway?

**Comment by stbrody** [comment]
Depends on the nature of the format change.  Also "break" isn't a binary - how it breaks is important.  If we somehow started corrupting data due to misinterpreting the structure of records, that'd be pretty bad.  Maybe not the most likely outcome, but also not impossible either.

The core issue is that if we don't do this before release, then for the rest of time any time we make a format change we have to think about "how is the original first version of ceramic going to react to these records/messages?".  If we do a little work now to future-proof ourselves, then the surface area of what we have to think about becomes much smaller and easier to reason about.
