### ISSUE TITLE
Include ceramic network in genesis record for documents created on networks other than mainnet

### ISSUE THREAD

**Issue by stbrody** [ceramicnetwork/js-ceramic#748]
to further isolate the networks and prevent accidentally taking over a DocID in mainnet with a document that was created on a testnet

**Comment by stbrody** [comment]
related to https://github.com/ceramicnetwork/js-ceramic/issues/662

**Comment by oed** [comment]
We made an explicit decision to not store the network in the genesis record. We can however have different pinstores for different networks.

**Comment by stbrody** [comment]
Yeah, I remember that this came up before, but I don't remember why we decided not to do it.  What's the downside?  Seems like a pretty small change that gives us a bunch more confidence that a bug won't cause us to accidentally pollute the mainnet docid space with docs that were intended for a testnet

**Comment by oed** [comment]
It introduces a lot of complexity upstream. Now every library that uses ceramic would need to know which network they post documents to (they might create the genesis record locally). So in IDX for example we would now need to introduce a configuration for which network you are using and the developer needs to be aware of this.

**Comment by stbrody** [comment]
Couldn't the ceramic http client query the daemon at startup to find out what network its on, and then automatically add the network into the genesis record when creating it?

**Comment by oed** [comment]
It could, but there might be cases where you want create the genesis record outside of the http client. 

cc @PaulLeCam for input on this discussion.

**Comment by stbrody** [comment]
well, in that case if you completely construct the genesis record from scratch manually, then fine that's the document, and we're no worse off than we are today.  But for the majority of users using the standard workflow, we can still add this without hurting their DX and by so doing add some extra protection

**Comment by michaelsena** [comment]
Wasn't this decided to future-proof Ceramic in the case that mainnet somehow becomes sharded?

**Comment by PaulLeCam** [comment]
The way IDX definitions work currently is that we create the signed commits directly, and then they can be deployed to any node and have the same IDs, so we can hardcode these IDs (in idx-constants notably).

If we were to have different IDs per network we'd need to generate these signed commits for each network and make the IDX client network aware. That's definitely possible but would need to dedicate time to update everything accordingly, and that would also add the same burden on developers so we should evaluate the additional DX downsides.

**Comment by stbrody** [comment]
Ah okay.  I'm convinced then that this is more effort than it's worth.  Thanks!
