### ISSUE TITLE
Ceramic.close() doesn't close all open handles and background work

### ISSUE THREAD

**Issue by stbrody** [ceramicnetwork/js-ceramic#754]
Steps to reproduce: add this test to `ceramic.test.ts`
```
  it.only('can close ceramic right after creating document', async () => {
    const ceramic = await createCeramic(ipfs1)
    await delay(1000)
    await ceramic.close()
  })
```

Have jest run just that test, and you get the warning:
```
Jest did not exit one second after the test run has completed.

This usually means that there are asynchronous operations that weren't stopped in your tests. Consider running Jest with `--detectOpenHandles` to troubleshoot this issue
```

**Comment by ukstv** [comment]
Note to self: look for FIXME 754

**Comment by ukstv** [comment]
As demonstrated by https://github.com/ceramicnetwork/js-ceramic/pull/992, not reproducible anymore. Closing.

**Comment by stbrody** [comment]
Still reproduces for me

**Comment by ukstv** [comment]
@stbrody You mean https://github.com/ceramicnetwork/js-ceramic/pull/992/files#diff-3dc086303a234c0aa9cb5b7b4b675827819e66906135448b777b221da01e0d60R50 hangs?

 Could you please, provide an example of the minimal test suite to reproduce, like I did with https://github.com/ceramicnetwork/js-ceramic/pull/992 ?

**Comment by stbrody** [comment]
@ukstv, finally got around to taking another look at this.  PR that repros the issue here: https://github.com/ceramicnetwork/js-ceramic/pull/1071

**Comment by ukstv** [comment]
@stbrody I feel like I solved the case. IPFS is to blame here. Apparently, when `ipfs.stop` promise fulfils, IPFS has still not freed all the resources. Adding `delay(1000)` after all the `ipfs.stop` statements fixes the issue.

**Comment by stbrody** [comment]
> @stbrody I feel like I solved the case. IPFS is to blame here. Apparently, when `ipfs.stop` promise fulfils, IPFS has still not freed all the resources. Adding `delay(1000)` after all the `ipfs.stop` statements fixes the issue.

Boom, I think that's exactly right.  Confirmed that that fixes it for me as well.  I also now seem to remember a problem in a different test at some point a while ago where starting a new ipfs instance too quickly after closing an old one would conflict in some way.  So yeah, definitely seems like js-ipfs has an issue with `.stop()` not actually waiting for all resources to be fully freed

**Comment by stbrody** [comment]
I guess we should just close this issue then if it's not actually a bug in ceramic?
