### ISSUE TITLE
Remove commit cache

### ISSUE THREAD

**Issue by stbrody** [ceramicnetwork/js-ceramic#757]
In https://github.com/ceramicnetwork/js-ceramic/issues/442 we added a [DocCache](https://github.com/ceramicnetwork/js-ceramic/blob/develop/packages/common/src/doc-cache.ts) to better manage our cache of recently accessed documents.  That DocCache includes a `_commitDocCache` which caches documents at specific document commits.  Currently the main use case for querying a document at a specific commit is from the anchor service.  https://github.com/3box/3box/issues/1300 is going to remove that behavior, so at that point we should probably remove the commit cache to save memory and decrease code complexity.  If a user tries to load a document at a specific commit, if the document is in the regular cache, and the commit being requests is part of that document's canonical history, it should be quick to create a version of the document tied to the requested commit, without having to load anything over the network, even without the commit cache.

**Comment by oed** [comment]
Requesting a document at a specific commit has two use cases right now besides what you mention:
* Schemas are always loaded with a specific commit
* Signatures made by a 3ID always include the commit of the 3ID document

**Comment by stbrody** [comment]
Ooh, good point, I had forgotten about the schema case, and didn't know about the 3id one.

That said, I'm still not totally convinced the commit cache actually makes sense.  So long as the document is in the main document cache, and the commit being requested is in the canonical document history, then we can serve those requests without doing network i/o, without needing to keep a separate cache that doubles our cache memory consumption for dubious gain

**Comment by ukstv** [comment]
Closing as no longer relevant.
