### ISSUE TITLE
Cannot read property 'commit' of undefined reading a doc

### ISSUE THREAD

**Issue by PaulLeCam** [ceramicnetwork/js-ceramic#777]
I got the following issue simply using the IDX CLI with the latest versions of Ceramic packages:

```
TypeError: Cannot read property 'commit' of undefined
    at DocCache.pin (node_modules/@ceramicnetwork/common/src/doc-cache.ts:62:20)
    at Object.add (node_modules/@ceramicnetwork/http-client/src/ceramic-http-client.ts:100:24)
```

**Comment by ukstv** [comment]
Mind posting commands here? `using IDX` is too vague for me to invoke behaviour you see. 

Console dump, screenshots, anything goes here.

**Comment by ukstv** [comment]
To remember:
```
running this command from the IDX CLI: https://github.com/ceramicstudio/idx-cli/blob/master/src/commands/index/inspect.ts
./bin/run index:inspect did:key:z6MkkzZm58o8u8qnhL2krQa1WK81ngFHErBCxaa6cPDNsLKm from the idx-cli repo with updated dependencies
```

**Comment by stbrody** [comment]
I believe this should be fixed by https://github.com/ceramicnetwork/js-ceramic/pull/752

**Comment by ukstv** [comment]
@PaulLeCam when you say "latest", does it mean latest from npm or latest from GitHub?

**Comment by PaulLeCam** [comment]
@ukstv latest from npm

**Comment by oed** [comment]
According to Zach this should be fixed in the latest release. Can you confirm Paul?

**Comment by PaulLeCam** [comment]
Confirmed, seems fixed in latest release.
