### ISSUE TITLE
Error: The operation rejected by operating system

### ISSUE THREAD

**Issue by purplealchemist** [ceramicnetwork/js-ceramic#796]
OS: Windows 10
npm version: 7.0.8
node: 15.1.0
This is what happens when I try to load the CLI from the Terminal (admin)
Command: i -g @ceramicnetwork/cli

C:\WINDOWS\system32>npm i -g @ceramicnetwork/cli
npm WARN ERESOLVE overriding peer dependency
npm WARN Found: @types/node@13.13.39
npm WARN node_modules/@ceramicnetwork/cli/node_modules/@types/node
npm WARN
npm WARN Could not resolve dependency:
npm WARN peer @types/node@"^8.0.0" from typestub-multihashes@0.0.4
npm WARN node_modules/@ceramicnetwork/cli/node_modules/typestub-multihashes
npm WARN   typestub-multihashes@"^0.0.4" from @ceramicnetwork/core@0.18.3
npm WARN   node_modules/@ceramicnetwork/cli/node_modules/@ceramicnetwork/core
npm ERR! code EPERM
npm ERR! syscall rename
npm ERR! path C:\Users\johnf\AppData\Roaming\npm\node_modules\@ceramicnetwork\cli
npm ERR! dest C:\Users\johnf\AppData\Roaming\npm\node_modules\@ceramicnetwork\.cli-sUnbfa4C
npm ERR! errno -4048
npm ERR! Error: EPERM: operation not permitted, rename 'C:\Users\johnf\AppData\Roaming\npm\node_modules\@ceramicnetwork\cli' -> 'C:\Users\johnf\AppData\Roaming\npm\node_modules\@ceramicnetwork\.cli-sUnbfa4C'
npm ERR!  [Error: EPERM: operation not permitted, rename 'C:\Users\johnf\AppData\Roaming\npm\node_modules\@ceramicnetwork\cli' -> 'C:\Users\johnf\AppData\Roaming\npm\node_modules\@ceramicnetwork\.cli-sUnbfa4C'] {
npm ERR!   errno: -4048,
npm ERR!   code: 'EPERM',
npm ERR!   syscall: 'rename',
npm ERR!   path: 'C:\\Users\\johnf\\AppData\\Roaming\\npm\\node_modules\\@ceramicnetwork\\cli',
npm ERR!   dest: 'C:\\Users\\johnf\\AppData\\Roaming\\npm\\node_modules\\@ceramicnetwork\\.cli-sUnbfa4C'
npm ERR! }
npm ERR!
npm ERR! The operation was rejected by your operating system.
npm ERR! It's possible that the file was already in use (by a text editor or antivirus),
npm ERR! or that you lack permissions to access it.
npm ERR!
npm ERR! If you believe this might be a permissions issue, please double-check the
npm ERR! permissions of the file and its containing directories, or try running
npm ERR! the command again as root/Administrator.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\johnf\AppData\Local\npm-cache\_logs\2021-01-14T16_58_40_574Z-debug.log

C:\WINDOWS\system32>

**Comment by valmack** [comment]
Thanks for reporting.

So not a  windows user but seems like you may be having the same issue mentioned here: https://stackoverflow.com/questions/22325031/npm-please-try-using-this-command-again-as-root-administrator

Can you try the proposed solution there and see if that works or not?
