### ISSUE TITLE
Document state isn't updated to reflect new pending state.

### ISSUE THREAD

**Issue by oed** [ceramicnetwork/js-ceramic#797]
The anchor status `scheduledAt` isn't updated if we get a `PENDING` response, see https://github.com/ceramicnetwork/js-ceramic/blob/develop/packages/core/src/anchor/ethereum/ethereum-anchor-service.ts#L169

The `response.json()` looks like this:
```js
{
  id: '9ab60499-5ac1-41b3-93c8-7288d312c23a',
  status: 'PENDING',
  cid: 'bagcqceralyma7vg2m7tgg3lxdtvdcdej5kosceppu3ga3ncfh5kpbk4edvra',
  docId: 'kjzl6cwe1jw147mb4t55jqr72cp9biw0ivntyzl4c4kyut0l5pehutgwitp56jm',
  message: 'Request is pending.',
  createdAt: 1610645376463,
  updatedAt: 1610645376463,
  scheduledAt: '2021-01-14T17:45:00.000Z'
}
```

**Comment by stbrody** [comment]
I'm not sure I follow.  What were you expecting to happen?

**Comment by oed** [comment]
Let's say the first response from the anchor service says `scheduledAt: 17:30` and the second request says `scheduledAt: 17:45` the document state will not be updated.

**Comment by stbrody** [comment]
Huh.  Why would the `scheduledAt` date change?  Are you actually seeing that come back from the CAS?

**Comment by oed** [comment]
I'm not sure why it would, but yeah I saw that happen. That's how I discovered the bug. I wouldn't prioritize this for now though.
