### ISSUE TITLE
Missing jest package

### ISSUE THREAD

**Issue by stanly-johnson** [ceramicnetwork/js-ceramic#823]
**Issue** : Running `npm i && npm test` in the root directory throws the following error
 `Test environment jest-environment-uint8array cannot be found. Make sure the testEnvironment configuration option points to an existing node module.`
 
 **Fix** : The cause is a missing package, can be fixed by 
`npm i --save-dev jest-environment-uint8array`

Is there a reason this package is not part of package.json? If not simply adding it there fixes the issue.

**Comment by oed** [comment]
This looks like an error in the package.json. Thanks for reporting! Feel free to submit a PR with a fix if you want :)
