### ISSUE TITLE
Cannot read property 'lastUpdate' of undefined

### ISSUE THREAD

**Issue by PaulLeCam** [ceramicnetwork/js-ceramic#827]
A POST call to `/api/v0/commits` returns a 500 response with `{"error":"Cannot read property 'lastUpdate' of undefined"}`

Steps to reproduce:
- run the Ceramic daemon v0.20.0
- run `idx bootstrap` with the latest version of `@ceramicstudio/idx-cli`
- in `ceramicstudio/3id-connect`:
  - update `3id-did-provider` to latest version
  - run `CERAMIC_API=http://localhost:7007 npm run start:demo`
- in `ceramicstudio/self.id`
  - update all dependencies to the latest version
  - change the following values in `src/constants.ts`:
    - CERAMIC_URL = 'http://localhost:7007'
    - CONNECT_URL = 'http://localhost:30001/index.html'
  - run `npm run dev` to start the app server
  - open http://localhost:3000
  - click the connect button
  - follow steps in MetaMask

**Comment by PaulLeCam** [comment]
In the browser console and the 500 shows up in the networking tab, but if you're running Next.js' dev server it should also show an error in the UI.

**Comment by PaulLeCam** [comment]
I could connect using different wallet addresses so that seems like one of these issues specific to a certain state of the document and/or Ceramic node that are hard to reproduce.
From the error message it seems to me it's a pretty common JS error trying to access the property of an object without a proper null-check first so even if we can't find an exact way to reproduce the issue might be worth checking the code that could cause this.

**Comment by oed** [comment]
Interesting @PaulLeCam could you share which eth-address so that we can find the documents that causes issues?

**Comment by PaulLeCam** [comment]
Sure, here is the address: `0xEA8B36116ff496DB2e47970cca7D98dd02C1c5A4`

**Comment by PaulLeCam** [comment]
@stbrody I'm not having the issue anymore using v0.20.1 of the CLI so we couldn't reproduce it further with Joel. I think we can close this issue if you want?

**Comment by stbrody** [comment]
Yeah, I'm still a little worried about how this happened.  The term `lastUpdate` appears in exactly one file in the js-ceramic code base [caip10-link-doctype-handler.ts](https://github.com/ceramicnetwork/js-ceramic/blob/adaa4f2527ef23a7762229cc79e92016be6fdeb9/packages/doctype-caip10-link-handler/src/caip10-link-doctype-handler.ts), and that code hasn't changed in a while.  The error most likely comes from [this line](https://github.com/ceramicnetwork/js-ceramic/blob/adaa4f2527ef23a7762229cc79e92016be6fdeb9/packages/doctype-caip10-link-handler/src/caip10-link-doctype-handler.ts#L108), which suggests that somehow we wound up with a signed commit without a `state.next.metadata` field, which should be impossible.  So this is a bit worrying, but without a way to repro I don't think there's anything we can do right now, so I'll go ahead and close this ticket for now until/unless the issue shows up again.
