### ISSUE TITLE
Change console.log calls to use logger

### ISSUE THREAD

**Issue by ukstv** [ceramicnetwork/js-ceramic#829]
I doubt it is a good idea to post it to console right away. I believe this kind of information should be properly logged.

**Comment by stbrody** [comment]
Agreed, we just don't have a good logging framework in place in js-ceramic yet.  We have [a project](https://github.com/ceramicnetwork/js-ceramic/issues/609) to add one.  As part of that project I plan to grep for every place we `console.log()` and change them to use the logger instead.

**Comment by stbrody** [comment]
I'm looking through the current places we access the `console` directly.  One of those places is [this line](https://github.com/ceramicnetwork/js-ceramic/blob/be2b472640d35165efeb61437b83a81f29e878be/packages/blockchain-utils-validation/src/blockchains/eosio.ts#L23) within the `validateLink` function for eosio blockchain validation, where it catches all exceptions and swallows them, logging a warning in the process.  I'm wondering - why are we swallowing all exceptions here?  The [ethereum](https://github.com/ceramicnetwork/js-ceramic/blob/be2b472640d35165efeb61437b83a81f29e878be/packages/blockchain-utils-validation/src/blockchains/ethereum.ts#L79-L81) and [filecoin](https://github.com/ceramicnetwork/js-ceramic/blob/be2b472640d35165efeb61437b83a81f29e878be/packages/blockchain-utils-validation/src/blockchains/filecoin.ts#L24-L26) integrations also swallow all exceptions, but without logging a warning.  The [cosmos](https://github.com/ceramicnetwork/js-ceramic/blob/be2b472640d35165efeb61437b83a81f29e878be/packages/blockchain-utils-validation/src/blockchains/cosmos.ts#L12), [near](https://github.com/ceramicnetwork/js-ceramic/blob/be2b472640d35165efeb61437b83a81f29e878be/packages/blockchain-utils-validation/src/blockchains/near.ts#L11), and [polkadot](https://github.com/ceramicnetwork/js-ceramic/blob/be2b472640d35165efeb61437b83a81f29e878be/packages/blockchain-utils-validation/src/blockchains/polkadot.ts#L8) integrations, however, do not swallow exceptions and allow them to bubble up to the calling code.

Would it be reasonable to remove the try/catch from eosio, ethereum, and filecoin implementations and just allow exceptions to bubble up the call stack?  The primary call site, in [caip10-link-doctype-handler.ts](https://github.com/ceramicnetwork/js-ceramic/blob/be2b472640d35165efeb61437b83a81f29e878be/packages/doctype-caip10-link-handler/src/caip10-link-doctype-handler.ts#L99) already throws exceptions so calling code must already be prepared for them.  Does that sound reasonable @oed @ukstv?

**Comment by stbrody** [comment]
Another place we access the console extensively is within the [ceramic-cli-utils.ts](https://github.com/ceramicnetwork/js-ceramic/blob/develop/packages/cli/src/ceramic-cli-utils.ts) file.  Since this file is only used from the CLI, and the CLI is all designed to run in the console anyway, I'm thinking it's fine to leave it accessing the console directly rather than trying to use the actual logger.  Does that seem reasonable @oed?

**Comment by stbrody** [comment]
Removing the `console.log` calls from within the `IpfsDaemon` and `IpfsTopology` classes depends on https://github.com/ceramicnetwork/js-ceramic/issues/1013 so we can initialize the logger outside of Ceramic.create() and pass it in
