### ISSUE TITLE
Document "anchorStatus" gets set to FAILED misleadingly when a later CID is anchored

### ISSUE THREAD

**Issue by stbrody** [ceramicnetwork/js-ceramic#838]
If there are multiple CIDs for single document pending anchor at the same time (say you create a document then immediately update it, or perform two updates in quick succession) such that both CIDs get considered in the same anchor batch, the request to anchor the first CID will "fail" but the request to anchor the second CID will succeed.  This is the correct behavior as anchoring the second CID logically includes anchoring the first as well.  But the js-ceramic instance that requested the anchor will see that the first CID anchor request failed, will set the document "anchorStatus" to failed, and will never apply the anchorCommit for the successful anchor of the second CID

**Comment by ukstv** [comment]
2 cents: it makes sense probably to have `OUTDATED` status that indicates there is a newer CID anchored.

**Comment by stbrody** [comment]
> 2 cents: it makes sense probably to have `OUTDATED` status that indicates there is a newer CID anchored.

Yeah, it does sort of make sense to distinguish between CID anchor totally failed, vs it was subsumed by the anchor of a later commit.  I'm not sure it's actually worth doing right now though since this will never really be surfaced to end users.  Right now the `anchorStatus` is document-wide, there's no way to check in js-ceramic what the anchor status of a specific CID is, so once you learn about the anchor of the later CID, the state of any earlier anchor requests is no longer relevant or surfaced anywhere.

I'm also hoping that all of this code changes as part of https://github.com/3box/3box/issues/1300
