### ISSUE TITLE
Move bootstrap mechanism to js-ipfs-ceramic and it directly in the ceramic daemon

### ISSUE THREAD

**Issue by ukstv** [ceramicnetwork/js-ceramic#849]
We have duplicated logic for setting up an IPFS node between the `js-ceramic` and `js-ipfs-ceramic` repos.  We should move all the logic to `js-ipfs-ceramic` and make `js-ceramic` explicitly depend on `js-ipfs-ceramic` and delegate to it for starting up ipfs

**Comment by valmack** [comment]
Related to https://github.com/ceramicnetwork/js-ipfs-ceramic/issues/22
