### ISSUE TITLE
Show timezone with anchorScheduledFor property

### ISSUE THREAD

**Issue by valmack** [ceramicnetwork/js-ceramic#897]
https://github.com/ceramicnetwork/js-ceramic/blob/8efe3daf4c8702a45a3d6489b587f5ce8045d908/packages/common/src/doctype.ts#L116

For example getting the doc state shows something like this
```
"anchorScheduledFor": "2/8/2021, 3:09:00 AM"
```

We should format this to something that shows the timezone

**Comment by oed** [comment]
Or always show time in the local timezone?

**Comment by carlbarrdahl** [comment]
Could you to use `new Date().toISOString()` here instead? 
https://github.com/ceramicnetwork/js-ceramic/blob/51b737542dc64cd3feac8af6c22fa32a81a48c8a/packages/common/src/utils/doctype-utils.ts#L93

It would return: `"2021-02-10T07:10:32.034Z"`

> The timezone is always zero UTC offset, as denoted by the suffix "Z".

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/toISOString
