### ISSUE TITLE
Handle errors in cli properly

### ISSUE THREAD

**Issue by v-stickykeys** [ceramicnetwork/js-ceramic#898]
Not all code is being handled in try/catch which causes unhandled promise rejections and results in the request hanging

For example 
```
http://localhost:7007/api/v0/pins/123
```
hangs indefinitely because the param is not a valid docid and an error gets thrown

```
(node:53865) UnhandledPromiseRejectionWarning: Error: fromString: requires base encoded string
```

but it does not get surfaced to the express handler, so no response is sent.

**Comment by stbrody** [comment]
Related to https://github.com/ceramicnetwork/js-ceramic/issues/611
