### ISSUE TITLE
Add S3 StateStore implementation

### ISSUE THREAD

**Issue by stbrody** [ceramicnetwork/js-ceramic#988]
Add a new `S3StateStore` implementation of the [StateStore interface](https://github.com/ceramicnetwork/js-ceramic/blob/8a86fb68b5f895f64e79a2585a5f854dd6c42088/packages/core/src/store/state-store.ts#L4)
We'll use the [s3leveldown](https://github.com/loune/s3leveldown) package for simplicity.
The implementation will live in the `cli` package and will be exposed via a new `--stateStore` flag, which will default to `leveldb` but will now also support `s3` as an option.

**Comment by oed** [comment]
A bit tangential but, do we want to keep adding flags to the cli, or should we start using the config file more for these type of things?

**Comment by stbrody** [comment]
> A bit tangential but, do we want to keep adding flags to the cli, or should we start using the config file more for these type of things?

Yeah that's a good point.  Probably cli flags should just be for things related to the client for creating/updating documents etc.  For the daemon configuration we should stick to the config file.
