### ISSUE TITLE
Create S3 state store bucket for dev-unstable

### ISSUE THREAD

**Issue by stbrody** [ceramicnetwork/js-ceramic#989]

**Comment by oed** [comment]
Why is this included in the implementation in js-ceramic?

**Comment by stbrody** [comment]
It's not, sorry this ticket probably should have been created in a different repo.  But it's needed in order to test the js-ceramic implementation

**Comment by oed** [comment]
Does the library we're intending to use not provide any default mocks? Makes sense to test it in our integration tests though!

**Comment by stbrody** [comment]
> Does the library we're intending to use not provide any default mocks? Makes sense to test it in our integration tests though!

I don't think so.  Since it implements the same API as leveldb, I kinda feel like just using leveldb directly is how you're supposed to test that your code is using the APIs right.  The main thing we'll have to test here is the actual S3 config parameters setup, and that can't be tested with a mock, only with the real deal.

**Comment by oed** [comment]
So we would only set this up for the integration test right?

**Comment by stbrody** [comment]
> So we would only set this up for the integration test right?

Correct, although ideally it'd be set up early so I can also use it for manual testing during development

**Comment by oed** [comment]
fyi @valmack @zachferland  ☝️
